config/crds/virt_v1alpha1_plan.yaml
config/samples/plan.yaml
pkg/apis/virt/v1alpha1/plan.go
pkg/controller/plan/controller.go
pkg/controller/plan/predicate.go

Add support for _ObservedGeneration_.
Assuming that:
1. The controller will only run on Kubernetes 1.10+
2. We can avoid the need for the controller to ever update the `Spec`.
we can leverage the `Status` _subresource_ which simplifies things a bit.
For example, the status update does not cause the `Generation` to be incremented so the ObservedGeneration can simply be set equal  to the Generation.

Add observed generation and samples.

---

config/crds/virt_v1alpha1_migration.yaml
config/crds/virt_v1alpha1_plan.yaml
config/samples/migration.yaml
config/samples/plan.yaml
pkg/apis/virt/v1alpha1/doc.go
pkg/apis/virt/v1alpha1/register.go

`make manifests` didn't update the CRDs, so I had to do it manually. I think I got all the instances of it.

Rename api group to 'virt.konveyor.io'

---

pkg/controller/plan/validation.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/controller.go
pkg/controller/provider/model/doc.go
pkg/controller/provider/model/ocp/doc.go
pkg/controller/provider/model/ocp/model.go
pkg/controller/provider/model/vsphere/doc.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/base/handler.go
pkg/controller/provider/web/doc.go
pkg/controller/provider/web/ns.go
pkg/controller/provider/web/ocp/client.go
pkg/controller/provider/web/ocp/doc.go
pkg/controller/provider/web/ocp/resource.go
pkg/controller/provider/web/provider.go
pkg/controller/provider/web/vsphere/client.go
pkg/controller/provider/web/vsphere/cluster.go
pkg/controller/provider/web/vsphere/datacenter.go
pkg/controller/provider/web/vsphere/datastore.go
pkg/controller/provider/web/vsphere/doc.go
pkg/controller/provider/web/vsphere/folder.go
pkg/controller/provider/web/vsphere/host.go
pkg/controller/provider/web/vsphere/network.go
pkg/controller/provider/web/vsphere/provider.go
pkg/controller/provider/web/vsphere/resource.go
pkg/controller/provider/web/vsphere/tree.go
pkg/controller/provider/web/vsphere/vm.go
vendor/github.com/konveyor/controller/pkg/inventory/model/client.go
vendor/github.com/konveyor/controller/pkg/inventory/model/model_test.go
vendor/github.com/konveyor/controller/pkg/inventory/model/table.go

Add type specific _extension_ filed to the `Provider` REST resource.  For both OCP and vSphere it needs to contain type specific counts needed by the UI.  Also added `?type=` parameter to provider collection for filtering.
The `Provider` resource is a little different in that technically it is part of the OCP (package) but really spans all provider types.  For consistency, I added a `Provider` model and update method signatures to use it.
Requires https://github.com/konveyor/controller/pull/18 (already vendor'd in)

Add extensions; counts to provider REST resource.

---

pkg/controller/provider/model/vsphere/tree.go

Fixed a flaw in the `Tree` builder when the leaf is a `Folder`.
Discovered this while testing a new folder tree endpoint that I then determined that I did not need.

Fix tree builder.

---

pkg/controller/provider/container/vsphere/reconciler.go

Batch object changes in DB transactions.

vSphere reconciler use DB transations.

---

config/crds/virt_v1alpha1_networkmap.yaml
config/crds/virt_v1alpha1_plan.yaml
config/crds/virt_v1alpha1_storagemap.yaml
pkg/apis/virt/v1alpha1/map.go
pkg/apis/virt/v1alpha1/plan.go
pkg/apis/virt/v1alpha1/provider.go
pkg/controller/host/controller.go
pkg/controller/host/validation.go
pkg/controller/map/network/controller.go
pkg/controller/map/network/validation.go
pkg/controller/map/storage/controller.go
pkg/controller/map/storage/validation.go
pkg/controller/migration/controller.go
pkg/controller/migration/migrate.go
pkg/controller/migration/validation.go
pkg/controller/plan/controller.go
pkg/controller/plan/validation.go
pkg/controller/provider/controller.go
pkg/controller/provider/validation.go
pkg/controller/provider/web/ocp/client.go
pkg/controller/validation/network.go
pkg/controller/validation/provider.go
pkg/controller/validation/storage.go
vendor/github.com/konveyor/controller/pkg/condition/condition.go
vendor/github.com/konveyor/controller/pkg/inventory/model/predicate.go
vendor/github.com/konveyor/controller/pkg/inventory/model/table.go
vendor/github.com/konveyor/controller/pkg/itinerary/simple.go

Update network & storage map CRs to reference a _pair_ of source/destination providers.
Create new `validation` package under controller to support validating shared CR data structures:
- Provider (ref)
- ProviderPair (ref)
- NetworkPair
- StoragePair
Added `description` to the Plan CR.  Needed by the UI.
The _Message constants were, well, messy and since conditions only created in one place, I got rid of the __Message const.
Requires: https://github.com/konveyor/controller/pull/24

Next iteration of valiations.

---

pkg/controller/map/network/controller.go
pkg/controller/map/network/validation.go
pkg/controller/map/storage/controller.go
pkg/controller/map/storage/validation.go
pkg/controller/plan/controller.go
pkg/controller/plan/validation.go
pkg/controller/provider/web/base/client.go
pkg/controller/provider/web/client.go
pkg/controller/provider/web/ocp/client.go
pkg/controller/provider/web/vsphere/client.go
pkg/controller/validation/network.go
pkg/controller/validation/provider.go
pkg/controller/validation/storage.go

This de-duplicates a good bit of code in the `web/ocp` and `web/vsphere` packages by introducing the convent of a `Resolver`.
The _Resolver_ resolves a REST resource object (kind) into a URL path.  Resolving the path **was** the main reason that the _type-sepecific_ package had to implement their own Client.
The provider API _Ready_ functionality has been centralized in the `ProviderClient` and rather than being called specifically, the provider _readiness_ is check on 404.  This also elliminates race conditions between the client making the GET call and the provider controller add/delete from inventory.
This PR also reduces complexity everywhere the provider REST API client is used in the other controllers because they no longer need to check for 206 _PartialContent_ because the …

API client improved.

---

pkg/controller/provider/web/vsphere/tree.go

Fix datacenter properties missing on tree/host view.
```
{
"kind": "Datacenter",
"object": {
"id": "",
"parent": null,
"name": "",
"selfLink": "/namespaces/openshift-migration/providers/vsphere/test/datacenters/datacenter-2760"
},
"children": null
},
```
Fixed:
```
{
"kind": "Datacenter",
"object": {
"id": "datacenter-2760",
"parent": {
"Kind": "Folder",
"ID": "group-d1"
},
"name": "Fake_DC",
"selfLink": "/namespaces/openshift-migration/providers/vsphere/test/datacenters/datacenter-2760"
},
"children": null
},
```

Fix datacenter properties missing on tree/host view.

---

config/crds/virt_v1alpha1_networkmap.yaml
config/crds/virt_v1alpha1_plan.yaml
pkg/apis/virt/v1alpha1/mapped/network.go
pkg/apis/virt/v1alpha1/plan.go
pkg/controller/plan/kubevirt.go
pkg/controller/provider/container/ocp/collection.go
pkg/controller/provider/container/ocp/reconciler.go
pkg/controller/provider/model/ocp/doc.go
pkg/controller/provider/model/ocp/model.go
pkg/controller/provider/web/base/handler.go
pkg/controller/provider/web/ocp/client.go
pkg/controller/provider/web/ocp/doc.go
pkg/controller/provider/web/ocp/namespace.go
pkg/controller/provider/web/ocp/netattachdefinition.go

Add `/namespaces` to provider inventory so the UI can list candidate target namespaces.
Add `Plan.Spec.TargetNamespace` as optional field.  This is where VMs will be migrated to.
Fixed issue:
- The _networkattachmentdefinitions_ `SelfLink` needs to be qualified by namespace.
- NetworkMap destination namespace & name not required when type=pod. 
- Fix (provider) API client to ensure that only URL params with values are replaced.  Else, the path will be missing segments with alters the path part of the URL in unpredictable ways.

Add support for user selected target namespace.

---

config/crds/virt_v1alpha1_host.yaml
config/crds/virt_v1alpha1_plan.yaml
pkg/apis/virt/v1alpha1/host.go
pkg/apis/virt/v1alpha1/plan.go
pkg/apis/virt/v1alpha1/plan/vm.go
pkg/apis/virt/v1alpha1/plan/zz_generated.deepcopy.go
pkg/apis/virt/v1alpha1/referenced.go
pkg/apis/virt/v1alpha1/zz_generated.deepcopy.go
pkg/controller/host/validation.go
pkg/controller/plan/builder/doc.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/kubevirt.go
pkg/controller/plan/migration.go
pkg/controller/plan/validation.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/vm.go
pkg/controller/validation/network.go
pkg/controller/validation/storage.go

Add `Secret` ref to `Host` CR.
Add `Host` validations.  Refactor to use shared provider validation.
Update controller flow to find Hosts in the same namespace and use the secret instead of the provider secret when found.  The logic also changed to create a Secret for each VirtualMachineImport CR.  Ideally we could create only the secrets needed but saving that for a future optimization.
Add VM.Host to the provider inventory.
Renamed and standardized variable for the provider API (as inventory) to clarify between that client and the k8s client.
Added `Referenced` object to be included in our CRs used to collect instances of resources fetched by validation to be used further downstream in reconcile logic.  The intent is to replace the stashing of resources in the Plan annotations in a …

Better support for hosts.

---

pkg/apis/virt/v1alpha1/plan.go
pkg/apis/virt/v1alpha1/snapshot/annotation.go
pkg/controller/plan/controller.go
pkg/controller/plan/validation.go

Replace plan snapshot with Referenced.
Also, noticed while troubleshooting that storing the validation result before running the migration would be helpful.  This should be safe since the Running, Succeeded, Failed conditions are durable.  Otherwise, if an error occurs while running the migration, the Plan will not reflect `Ready`.

Replace plan snapshot with Referenced.

---

pkg/apis/virt/v1alpha1/zz_generated.deepcopy.go
pkg/controller/plan/builder/doc.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/kubevirt.go

Propagate VM target name from the source provider.
Given the need for provider _type_ content in the VirtualMachineImportSpec, I think it makes sense to rename the Builder.Source() to Builder.Import() and broaden its scope.  This would be better than adding an additional method to the `Builder` interface because it's simpler and supports more future needs.

Propagate VM target name.

---

pkg/apis/virt/v1alpha1/zz_generated.deepcopy.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/controller.go

Moved the plan update (to reflect progress) to execute() so the plan is not double updated unnecessarily.

Update plan to reflect progress as needed in execute().

---

config/crds/virt_v1alpha1_host.yaml
pkg/apis/virt/v1alpha1/host.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/host.go

This pull request adds the `thumbprint` attribute to the Host model.
The data is collected from VMware via `MOR:HostSystem.summary.config.sslThumbprint`.

Add thumbprint to Host model

---

pkg/controller/host/controller.go
pkg/controller/host/validation.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/model/vsphere/doc.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/host.go
pkg/controller/provider/web/vsphere/vm.go

Focused mostly on Host and some VM properties.
VM:
- disk storage used.
- fault tolerance enabled.
- has SRIOV support.
- shared (each disk).
Host:
- thumbprint
- cpuSocket
- cpuCores
- list of network adapters with (name, mtu, linkspeed) as candidate networks for disk transfer.
Add support for distributed virtual PortGroup & Swtich in the inventory and incorporate when deriving the Host adapter list used as candidates for disk transfer networks.
Also:
- Inject thumbprint on Host (in inventory) in VMIO secret when Host CR is matched.
- Host secret validation no longer requires _thumbprint_.
- Fix host controller logging _ProviderNotFound_ error (routine).
closes #36 
closes #48 
closes #49 
closes #65

Provider inventory iteration 8

---

Dockerfile

This pull request switches to using Red Hat's UBI8 image to build the `virt-controller` container image.

Switch build base image to ubi8/go-toolset

---

pkg/controller/provider/container/vsphere/model.go

Fixed SEGV caused when pNIC.LinkSpeed is nil.
```
goroutine 592 [running]:
github.com/konveyor/virt-controller/pkg/controller/provider/container/vsphere.(*HostAdapter).Apply(0xc002637080, 0xc0027038f0, 0x5, 0xc002703920, 0xa, 0xc002703940, 0x6, 0xc002714600, 0xf, 0x10, ...)
/opt/app-root/src/github.com/konveyor/virt-controller/pkg/controller/provider/container/vsphere/model.go:347 +0x60e
github.com/konveyor/virt-controller/pkg/controller/provider/container/vsphere.Reconciler.applyEnter(0xc000b67a80, 0x31, 0xc0000fc8c0, 0xc000b788c0, 0x1de1d60, 0xc0016906e0, 0x1dd2ec0, 0xc00176dd20, 0xc0009fddc8, 0x8, ...)
/opt/app-root/src/github.com/konveyor/virt-controller/pkg/controller/provider/container/vsphere/reconciler.go:716 +0xaf
github.com/konveyor/virt-controller/pkg/controller/provider/contain …
```

Fixed SEGV caused when pNIC.LinkSpeed is nil.

---

pkg/controller/provider/web/ocp/netattachdefinition.go

The NetworkAttachmentDefinition (NAD) `SelfLink` is constructed using the provider namespace instead of the NAD resource namespace.  As a result, the plan controller (using the client) is looking in the wrong namespace which results in NotFound validation condition.

Fix NAD selfLink.

---

pkg/controller/provider/controller.go
pkg/controller/provider/web/base/client.go
pkg/settings/inventory.go
vendor/github.com/konveyor/controller/pkg/inventory/web/web.go

This pull request enabled TLS for the inventory container. If a secret name is passed as the `TLS_SECRET_NAME` environment variable, the TLS configuration is enabled and passed to the inventory container (see [konveyor/controller#29](https://github.com/konveyor/controller/pull/29)). The web client is also configured to use TLS and uses the openshift-signer CA certificate to validate the inventory service certificate.
Depends on https://github.com/konveyor/controller/pull/29.

Enable TLS for inventory

---

pkg/settings/inventory.go

Follow-up for https://github.com/konveyor/virt-controller/pull/79 to fix the TLS settings expansion.

Fix TLS settings for inventory

---

pkg/controller/plan/builder/vsphere/builder.go

ResourceMapping sections of VirtualMachineImport CRs doesn't have the NetworkMapping.Type (pod/multus).
When only one network is mapped, this works because VMIO default is pod. However, it fails when there's more than one network as they all default to `pod` and a VM can only be connected once to the pod network.
This pull request propagates the type to the VMIO ResourceMapping.

Add type to VMIO network mapping

---

pkg/controller/provider/web/base/client.go
pkg/settings/inventory.go

With #79 merged, the inventory client doesn't find the right environment variables on the `main` container, so it is still trying to connect to http://localhost:8080. This pull request adds a `API_TLS_ENABLED` environment variable that affects the scheme.
The `API_HOST` and `API_PORT` environment variables can also be used to affect the rest of the base URL. This is done in [konveyor/virt-operator#44](https://github.com/konveyor/virt-operator/pull/44) to ensure the hostname matches the certificate subject.

Fix inventory client when TLS is enabled

---

pkg/controller/plan/builder/doc.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/kubevirt.go
pkg/controller/plan/migration.go

This pull request changes the VirtualMachineImport build to:
- Snapshot the plan map in `plan.kubevirt.buildImport` and passing it to `plan.builder.vsphere.builder.Import`.
- Modify `plan.builder.vsphere.builder.Mapping` to embed the `VMImport.Spec.Source.Vmware.Mappings`.
- Modify `plan.builder.vsphere.builder.Mapping` to write the mappings in `VMImport.Spec.Source.Vmware.Mappings`.
Closes #84

Use internal mapping in VirtualMachineImport CR

---

pkg/controller/provider/web/base/client.go
pkg/settings/inventory.go

Fails with _file-not-found_ unless a certificate exists at /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt even with TLS  not enabled.  Also, cache the transport to avoid loading it for each Get() request.  When checking VMs, this could be thousands of times.  Although could have copied my test CA to the pod location (/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt) when running/testing locally, it was a bit of a pain.  The CA setting provides completeness and more flexibility.
Reduced _some_ complexity (deep nesting) in Settings.Inventory.Load() re: TLS settings.

Fix TSL when not enabled skip loading CA certificate.

---

pkg/controller/provider/container/ocp/collection.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/controller.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/resource.go
pkg/controller/provider/web/vsphere/vm.go
pkg/controller/provider/xavier/base/client.go
pkg/controller/provider/xavier/base/doc.go
pkg/controller/provider/xavier/doc.go
pkg/controller/provider/xavier/vsphere/adapter.go
pkg/settings/inventory.go
vendor/github.com/konveyor/controller/pkg/inventory/model/client.go
vendor/github.com/konveyor/controller/pkg/inventory/model/model_test.go

Initial integration with MA (xavier) validation service.
Adds:
- _Xavier_ client.
- A `revision` property to all resources.
- A `revisionAnalyzed` property which indicates the `revision` reflected in the analytics `concerns`.
- Triggered by _watch_ on vSphere Cluster and VM database entities.  Likely add a _watch_ on other kinds (Eg: Network) in the next iteration.
Need operator to set:
- XAVIER_URL
- XAVIER_USER
- XAVIER_PASSWORD
in the virt-controller configMap.  Related PR (TBD).  Re: [issue/43](https://github.com/konveyor/virt-operator/issues/43).
Also, includes /vendor change for _common_ controller lib fix.
Requires: https://github.com/konveyor/controller/pull/34

Add integration with MA.

---

.github/workflows/pull_request.yml
README.md

When enabling Github Actions, we need to setup the Golang environment before running the tests.

Add Golang setup step

---

pkg/apis/forklift/v1alpha1/host.go
pkg/apis/forklift/v1alpha1/zz_generated.deepcopy.go
pkg/controller/host/validation.go
pkg/controller/plan/builder/vsphere/builder.go

The secret referenced in the `Host` CR is optional.  The CRD specified this but not completely supported in the controller.  Needed to relax the host validation and handle appropriately when building the VMIO secret.

Optional host secret not fully supported.

---

pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/base/client.go
pkg/controller/provider/web/ocp/base.go
pkg/controller/provider/web/ocp/doc.go
pkg/controller/provider/web/ocp/provider.go
pkg/controller/provider/web/vsphere/base.go
pkg/controller/provider/web/vsphere/cluster.go
pkg/controller/provider/web/vsphere/datacenter.go
pkg/controller/provider/web/vsphere/datastore.go
pkg/controller/provider/web/vsphere/doc.go
pkg/controller/provider/web/vsphere/folder.go
pkg/controller/provider/web/vsphere/host.go
pkg/controller/provider/web/vsphere/network.go
pkg/controller/provider/web/vsphere/provider.go
pkg/controller/provider/web/vsphere/resource.go
pkg/controller/provider/web/vsphere/tree.go
pkg/controller/provider/web/vsphere/vm.go
vendor/github.com/konveyor/controller/pkg/inventory/model/predicate.go

Begin adding support for extended query parameters starting with `name`.
Eg: `https://inventory/namespaces/openshift-migration/providers/vsphere/test/networks?name=VM_Storage`

Provider inventory: Support query by name.

---

pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/vm.go

Add VM.devices (list) instead of individual xxxSupported fields.
Taking the opportunity provided by switching to OPA to model the devices information more naturally.  This will also provide more flexibility moving foward.

Add VM.devices instead of individual xxxSupported fields.

---

pkg/controller/host/controller.go
pkg/controller/host/validation.go
pkg/controller/map/network/controller.go
pkg/controller/map/storage/controller.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/controller.go
pkg/controller/plan/kubevirt.go
pkg/controller/plan/migration.go
pkg/controller/plan/validation.go
pkg/controller/provider/model/vsphere/tree.go
pkg/controller/provider/web/base/client.go
pkg/controller/provider/web/client.go
pkg/controller/provider/web/ocp/client.go
pkg/controller/provider/web/vsphere/client.go
pkg/controller/validation/network.go
pkg/controller/validation/storage.go

Currently all errors from building and creating the VMIO CR are bubbled up to main Reconcile(), traced and the reconcile re-queued.  Instead, errors associated with building/creating the CR should be captured as an `Error` on the VM pipeline structure itself.  As a result, the individual import would be failed.
To accomplish this, we really needed to include more contextual information in the errors being bubbled up.  To do this, we also needed raise/check errors based on error type using errors.As() instead of errors.Is() which does a direct comparison.  This is because to include the contextual information, we need to create a _new_ instance of the error.

Improved migration error handling; Typed errors using errors.As().

---

pkg/controller/provider/web/base/handler.go
pkg/controller/provider/web/vsphere/base.go
pkg/controller/provider/web/vsphere/client.go

The Finder.ByRef() needs to pass the `detail=1` param when the ref specifies the `name` instead of the ID because it uses the web.Client.List() which by default will not include details.  Find() is intended to behave like `Get()` and include details by default.

Fix Finder.ByRef() to include detail param.

---

config/crds/forklift_v1alpha1_plan.yaml
config/crds/forklift_v1alpha1_provisioner.yaml
config/crds/forklift_v1alpha1_storagemap.yaml
config/samples/provisioner.yaml
pkg/apis/forklift/v1alpha1/mapped/storage.go
pkg/apis/forklift/v1alpha1/provisioner.go
pkg/controller/plan/builder/doc.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/context/doc.go
pkg/controller/plan/context/migration.go
pkg/controller/plan/controller.go
pkg/controller/plan/kubevirt.go
pkg/controller/plan/migration.go
pkg/controller/provider/model/ocp/model.go
pkg/controller/provider/web/ocp/namespace.go
pkg/controller/provider/web/ocp/netattachdefinition.go
pkg/controller/provider/web/ocp/provider.go
pkg/controller/provider/web/ocp/storageclass.go
pkg/controller/provider/web/vsphere/provider.go
vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/resourcemapping_types.go
vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/virtualmachineimport_types.go
vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/vmimportconfig_types.go
vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/zz_generated.deepcopy.go

Add support for passing _volumeMode_ and _accessMode_ to VMIO.
Both modes may be passed in the destination storage structures in the forklift plan and storageMap CRs.
When not passed, the `Provisioner` CR is used to provide defaults.
To provide this, the destination provider API client needed to be available to the vSphere `Builder` which, currently, it is not.  Rather than update the _Builder_ interface with the additional inventory client, it seemed like a better long term investment was to create a `Context` object that could be passed and/or used in other object aggregation.
The VMIO dependencies need to be updated.
Lastly, the OCP REST resources `Object` field needed to contain the concrete _type_ instead of _interface{}_ so when the other controllers used the REST client, the actual …

Support volume/access modes.

---

Dockerfile

With the transition to go modules, the Dockerfile needs to be updated to leverage it.

Fix Dockerfile after #126

---

pkg/controller/plan/builder/vsphere/builder.go

Set `volumeMode` in the VMIO CR mapping only when specified or defaulted.

Set volumeMode only when specified or defaulted.

---

cmd/manager/main.go
pkg/controller/controller.go
pkg/settings/metrics.go
pkg/settings/settings.go

Add support for Prometheus metrics endpoint settings.
Set environment variable `METRICS_PORT` in the deployment.  Eg: 8888.
```
{"level":"info","ts":1608233315.162371,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8888"}
```

Support metrics settings.

---

go.mod
go.sum

Bump dependency: controller 0.2.4.
Disables metrics endpoint for remote watch managers used for OCP provider data collection.

Bump dependency: controller 0.2.4.

---

pkg/controller/plan/controller.go
pkg/controller/plan/predicate.go
pkg/controller/plan/validation.go

The plan controller was watching the `Host` CR because it validated that ALL `Host` in the same namespace as the plan had the ready condition.  There are two problems with this:
- The implementation is flawed.  I needed to have a custom event handler that would re-map the Host event into an event for each `Plan` by querying them.  Without this, the Host namespace and name in the Host event was passed to the Plan reconciler.
- Blocking all plans when a (potentially unrelated) host is not READY adds little value and subject to all kinds of race conditions.  Also, seems wrong to block unrelated plan.
A symptom of this is the plan reconciler getting events for plan (namespace/name) that does not exist.

Plan controller Host watch removed.

---

pkg/controller/host/validation.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/builder/vsphere/host.go

The connection test was still using the `thumbprint` in the secret instead of the thumbprint for the host in the inventory.

Fix host connection test.

---

pkg/controller/host/controller.go
pkg/controller/map/network/controller.go
pkg/controller/map/storage/controller.go
pkg/controller/migration/controller.go
pkg/controller/plan/controller.go
pkg/controller/provider/controller.go

General reconciler improvements and standardization.
We don't want to trace provider-not-ready errors.  This add a lot of unnecessary noise in the logs.

Reconciler improvements.

---

Makefile

Fix port collision between the provider API and metrics.

Define METRICS_PORT to fix make run.

---

pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/model/vsphere/tree.go
pkg/controller/provider/web/vsphere/doc.go
pkg/controller/provider/web/vsphere/tree.go
pkg/controller/provider/web/vsphere/workload.go

Add a _new_ composite resource (endpoint) to the provider inventory/API.  Borrowing the term from _vSphere_, the new resource is called a _"workload"_ and contains all fields as a `VM` but with the `host` field redefined to be the de-referenced `Host` resource.  The (de-referenced) `Host` resource has all of the same properties as a regular `Host` but with an additional `cluster` property.  The `Cluster` has all the same fields a a regular `Cluster` but with an additional `datacenter` field which contains the `Datacenter`.
This composite resource is generally useful.  However, an immediate use case is: for the policy-agent to evaluate rules against the VM and its host and cluster.
To support this, the _tree_ functionality in the model and web layers was expanded to support:
- Build a tree …

Add a new composite VM resource to the provider API

---

pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/controller.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/ocp/provider.go
pkg/controller/provider/web/vsphere/vm.go
pkg/controller/validation/policy/client.go
pkg/settings/inventory.go
pkg/settings/policy.go
pkg/settings/settings.go

Integration with OPA-based validation service.
The `Concerns` resource modified to match what is provided by the validation service.
Add fields to the VM:
- PolicyVersion
- RevisionValidated.
Updated DB model watches:
On cluster updated:  List hosts and mark VM associated with each host as needing to be re-validated.
On host updated:List VMs and mark them as needing to be re-validated.
On VM created/updated: validate VM of the `RevisionValidated` != `Revision`.
Periodically search for VMs with `RevisionValidated` != `Revision` || `PolicyVersion != <latest version>`.  
This is needed to handle cases:
- The validation service is not available when the DB model is created/deleted.
- The policy (rules) version running in the validation service change.
- Validation fails.

Integration with PA-based validation service.

---

pkg/controller/provider/web/vsphere/cluster.go
pkg/controller/provider/web/vsphere/datacenter.go
pkg/controller/provider/web/vsphere/tree.go

Provider API fixes:
- Add datastore, network, cluster, vm folders to Datacenter REST resource.
- Fixed `dasVms` json tag.
- Fixed host tree missing VM leaf nodes.

Provider API fixes.

---

pkg/controller/map/network/validation.go
pkg/controller/map/storage/validation.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/builder/vsphere/host.go
pkg/controller/plan/controller.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/controller.go
pkg/controller/provider/model/vsphere/tree.go
pkg/controller/provider/web/base/client.go
pkg/controller/provider/web/ocp/provider.go
pkg/controller/provider/web/vsphere/datastore.go
pkg/controller/provider/web/vsphere/host.go
pkg/controller/provider/web/vsphere/network.go
pkg/controller/provider/web/vsphere/provider.go
pkg/controller/provider/web/vsphere/tree.go
pkg/controller/validation/network.go
pkg/controller/validation/provider.go
pkg/controller/validation/storage.go
pkg/settings/settings.go

The original philosophy was the by wrapping errors at all levels would:
- Ensure errors got wrapped.
- Easier to code review because it's consistent.
After living with it for a while it seem apparent that neither are true.  Wrapping only where errors are returned by external packages is:
- reliable
- straight forward to code review
- reduces code noise.

Wrap error (only) at the edge.

---

pkg/controller/plan/context/migration.go

Use non-cached client even when destination is host.
https://bugzilla.redhat.com/show_bug.cgi?id=1928011

Bug-1928011: Use non-cached client even when destination is host.

---

pkg/controller/map/network/validation.go
pkg/controller/map/storage/validation.go

If a Map's source provider was invalid for a reason other than not being ready, it would attempt to validate the source network or storage and fail because the referenced provider would be nil. This fixes the condition checks to include `SourceProviderNotValid`, which short circuits the validation and prevents the segfault.

Fix storage and network map validation segfault

---

pkg/controller/plan/migration.go

This marks the current pipeline step complete when the VM is canceled. Required for https://github.com/konveyor/forklift-ui/pull/400

Mark active step complete when VM is canceled

---

pkg/apis/forklift/v1alpha1/mapping.go

Having the `ref:` tag on the provider.Pair shadows the fields on provider.Pair.
The ref _mapper_ will not drill into a _struct_ field with the tag.

Fix mapping CRs reference watch on provider.

---

pkg/controller/plan/kubevirt.go
pkg/controller/plan/migration.go

Convert `KubeVirt` to use generated names.  This includes finding resources by label.
This also includes consolidating the _ensureXX()_ to build the VM Import CR and associated secret.

VMIO CR generated names.

---

pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/vm.go

Add VM snapshot property.
```
"snapshot": {
"kind": "VirtualMachineSnapshot",
"id": "snapshot-3134"
},
```
Blank when the VM has not current snapshot.
```
"snapshot": {
"kind": "",
"id": ""
},
```

Add VM snapshot property.

---

pkg/controller/plan/kubevirt.go

Because `builder.Secret` creates a Secret with `StringData` instead of `Data`, `ensureSecret` needs to use the new secret's `StringData` to update the existing secret.

Use StringData to update secret in ensureSecret

---

pkg/controller/plan/kubevirt.go

The UI doesn't schedule a cutover right away, so we need to be able to start a plan with no cutover date.

Don't set a default cutover

---

pkg/controller/plan/migration.go
pkg/controller/plan/scheduler/doc.go
pkg/controller/plan/scheduler/vsphere/scheduler.go
pkg/controller/plan/scheduler/vsphere/scheduler_test.go

This introduces a stateless scheduling mechanism for vSphere, which restricts the number of VM migrations that can be started across all plans using the same source. 
* Each host can have a number of disks in flight equal to `MAX_VM_INFLIGHT`. VMs can be scheduled if there are enough slots free on the host to accommodate the number of disks attached to the VM. 
* Each Plan can start at most a single VM on each reconcile, in order to allow other Plans an opportunity to schedule a VM.
* `migration.Run` has been refactored to first find all the Plan's started VM migrations and step through their pipelines. Then it acquires the next VM that can be scheduled if any, and steps through its pipeline.

Introduce vSphere migration throttling

---

pkg/controller/plan/scheduler/vsphere/scheduler.go

This fixes a bug with the Scheduler importing the VM struct from the wrong package, resulting in reconciles failing.

Backport to Release v2.0.0: Make Scheduler import web.VM, not model.VM

---

pkg/controller/plan/builder/doc.go
pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/migration.go

`buildPipeline` uses the disk backing file name from
the inventory to create the VM pipeline tasks, but
`updatePipeline` uses the disk backing name from the
DataVolumes to find those tasks.
When VMIO creates a DataVolume for a VM that is being warm
migrated, it creates a snapshot first. This will cause
the disk backing file name to differ from what the inventory
saw, and means `updatePipeline` won't be able to find
the task that `buildPipeline` created.
This patch causes the backing file suffixes to be trimmed
before comparing them, enabling pipeline updates to
work correctly.

Trim suffix from disk backing file names to fix task name comparisons

---

go.mod
go.sum
pkg/controller/map/network/controller.go
pkg/controller/map/network/handler/doc.go
pkg/controller/map/network/handler/ocp/doc.go
pkg/controller/map/network/handler/ocp/handler.go
pkg/controller/map/network/handler/vsphere/doc.go
pkg/controller/map/network/handler/vsphere/handler.go
pkg/controller/map/network/predicate.go
pkg/controller/map/network/validation.go
pkg/controller/map/storage/validation.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/controller.go
pkg/controller/provider/web/base/client.go
pkg/controller/watch/doc.go
pkg/controller/watch/handler/doc.go
pkg/controller/watch/handler/handler.go
pkg/controller/watch/handler/watch.go

PoC for remote watch of inventory.
Starting with the NetworkMap controller using the well established _factory_ pattern.
Adds the following new packages:
- **/controller/watch/handler** - Base _inventory_ watch event handler.
- **/controller/map/network/handler** - root _inventory_ watch event handler. package with factory.
- **/controller/map/network/handler/ocp** -  OCP _inventory_ watch event handler.
- **/controller/map/network/handler/vsphere** - vSphere _inventory_ watch event handler.
**Requires**:  https://github.com/konveyor/controller/pull/55
---
Each controller will:
- add a `Channel` source to support injecting events into the controller work queue.
- update the provider predicate to be composed of a `WatchManager` and ensure _inventory_ watches are created when a `Provider` …

Watch inventory.

---

go.mod
go.sum
pkg/controller/host/predicate.go
pkg/controller/map/network/predicate.go
pkg/controller/map/storage/predicate.go
pkg/controller/plan/controller.go
pkg/controller/plan/predicate.go
pkg/controller/provider/web/base/auth.go
pkg/controller/provider/web/base/auth_test.go
pkg/controller/provider/web/base/client.go
pkg/controller/provider/web/base/handler.go
pkg/settings/inventory.go

Token must have verb="*" on the `Provider` CR to access associated endpoints.
Perform TokenReview/SAR.  The API is hit many times per second so the result is cached for 10 seconds to prevent spamming the API server and for better performance.
Requires: https://github.com/konveyor/controller/pull/57
Also fixes some issues related to watching other forklift resources and a SEGV in the plan controller.  These issues introduced in: 
- https://github.com/konveyor/forklift-controller/pull/201
-  https://github.com/konveyor/forklift-controller/pull/194

Provider API: add authorization.

---

pkg/controller/provider/web/ocp/provider.go

Add counts to the OCP provider resource.
- vmCount
- storageClassCount
- networkCount
Looks like Fabien added this in Feb in https://github.com/konveyor/forklift-controller/pull/150 but got accidentally reverted.
Re-add but without namespceCount no longer needed (or relevant).

Add OCP provider counts.

---

go.mod
go.sum
pkg/controller/host/handler/vsphere/handler.go
pkg/controller/map/network/handler/vsphere/handler.go
pkg/controller/map/storage/handler/vsphere/handler.go
pkg/controller/plan/handler/vsphere/handler.go
pkg/controller/provider/controller.go

Fix inventory watch handler for `Deleted` resources.  The logic that resolves the Refs in each CR is flawed because in the case of a `Deleted` resource, the lookup will never be successful which results in the affected CR never being matched.  This logic replaced with _smart_ comparison of the Ref to the deleted/changed resource.  This does not affect OCP resources.
Also, noticed that the predicate should be handling renamed vSphere resources.

Fix inventory watch handler for Deleted resources.

---

pkg/controller/provider/container/vsphere/watch.go
pkg/controller/validation/policy/client.go
pkg/settings/policy.go

Shorten the validation search interval.  10 minutes seems much more reasonable then 30 seconds.  The watch events should keep up and the search is only needed for in case the watch events queue overflows.
Also, update the search file list VM in pages to limit memory footprint.

Adjust VM validation search settings and paging.

---

pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/plan/kubevirt.go

The StorageClass name lookup needs to be done using `client.Find(model, Ref)` instead of `client.Get(object, id)`.
The VM migration was not failing because the error was not being returned properly.
Best I can tell, ALL of the VMIO CRs would not be created with a storage mapping.
https://bugzilla.redhat.com/show_bug.cgi?id=1948965

Bug: 1948965 - Fix storageclass lookup and swallowed error.

---

pkg/controller/provider/controller.go

Use a cached client in provider controller.  Looks like it was originally created using a non-cached client.  I think this is an unnecessary _carry over_ from the crane `discovery` controller.
Root cause for: https://bugzilla.redhat.com/show_bug.cgi?id=1948975 because the non-cached client will leave the object `kind` and `apiVersion` blank.  As a result, when it's is fetched from inventory, the REST resource cannot be used by the UI to create an OwnerReference.

Use cached client in provider controller.

---

pkg/controller/plan/builder/vsphere/builder.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/vm.go

If a VMware VM connection state is not "Connected", the migration will fail. This pull request adds the `ConnectionState` attribute for the VM in the VMware inventory and errors out when building the VirtualMachineImport CR if the value is not `VirtualMachineConnectionStateConnected`.
Fixes #138.

Skip VMs that are not connected

---

pkg/controller/plan/builder/vsphere/builder.go

When a plan is set to be warm, the VM needs to have Changed Block Tracking (CBT) enabled, in order to identify the delta between two snapshots. Without this feature, the warm migration will not work.
In VMIO, the check for CBT will raise a validation error and requeue, which leaves the migration stuck from a Forklift perspective. So, we decided to add a check in the plan migration builder to fail VMs with CBT disabled directly in the controller. This will avoid creating a VirtualMachineImport CR that will be stuck.
This pull request implements this new behavior.

[BZ 1951395] Warm Migration - Skip VMs with CBT disabled

---

pkg/controller/plan/builder/vsphere/builder.go

Fix compiler error introduced by [pull/223](https://github.com/konveyor/forklift-controller/pull/223).
```
[jortel@f28a forklift-controller][AWS4]$ make manager
/home/jortel/go/bin/controller-gen object:headerFile="./hack/boilerplate.go.txt" paths="./..."
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
pkg/controller/plan/builder/vsphere/builder.go:110:28: vm.changeTrackingEnabled undefined (type *"github.com/konveyor/forklift-controller/pkg/controller/provider/web/vsphere".VM has no field or method changeTrackingEnabled, but does have ChangeTrackingEnabled)
make: *** [Makefile:45: vet] Error 2
```

Fix compiler error introduced by pull/223.

---

pkg/controller/provider/container/ocp/collection.go

Fix 1942091, Namespace watch.  Cut-n-paste error.
https://bugzilla.redhat.com/show_bug.cgi?id=1942091

Fix 1942091, Namespace watch.

---

go.mod
go.sum
pkg/controller/base/controller.go
pkg/controller/hook/controller.go
pkg/controller/host/controller.go
pkg/controller/host/validation.go
pkg/controller/map/network/controller.go
pkg/controller/map/storage/controller.go
pkg/controller/migration/controller.go
pkg/controller/plan/controller.go
pkg/controller/provider/controller.go
pkg/controller/provider/validation.go
pkg/controller/validation/policy/client.go
pkg/controller/watch/handler/handler.go

Add base reconciler to deduplicate fields and begin/end reconcile behavior and refit controllers.
Add additional logging statements to `controller.go` in each controller.
Add additional logging statements to other top level packages.
Requires:
- https://github.com/konveyor/controller/pull/65
- https://github.com/konveyor/controller/pull/66

More logging.

---

Dockerfile
go.mod
go.sum
pkg/controller/provider/model/vsphere/model.go

Add VM indexes; Install tar in Dockerfile; controller 0.3.4.
The indexes are needed for recurring search for VM that needs to be validated.
`tar` is needed to support `oc cp` command so we can download the files created by the profiler.

Add VM indexes; Install tar in Dockerfile; controller 0.3.4.

---

pkg/apis/forklift/v1alpha1/host.go
pkg/controller/host/controller.go
pkg/controller/host/handler/vsphere/handler.go
pkg/controller/map/network/handler/ocp/handler.go
pkg/controller/map/network/handler/vsphere/handler.go
pkg/controller/map/storage/handler/ocp/handler.go
pkg/controller/map/storage/handler/vsphere/handler.go
pkg/controller/plan/handler/ocp/handler.go
pkg/controller/plan/handler/vsphere/handler.go
pkg/controller/provider/web/base/client.go
pkg/controller/validation/policy/client.go

1. Detect ensure watch error and NOT attempt log the watch.  Caused SEGV when (2) failed.
2. Disabled `ForceAttemptHTTP2` because it was causing _websocket_ connection to fail.  Regression added by https://github.com/konveyor/forklift-controller/pull/229.
3. Fix policy-agent determining TLS using the (incorrect) setting.  Regression added by https://github.com/konveyor/forklift-controller/pull/229.
4. Add Host watch on referenced secret.  Testing and noticed this.

Detect ensure watch error.

---

pkg/apis/forklift/v1beta1/ref/ref.go
pkg/controller/plan/adapter/vsphere/builder.go

When the VirtualMachineImport builder fails, the VM MoRef is not user friendly in the error. This pull request adds the VM name.

BZ 1952312 - Add VM name to builder error messages

---

pkg/controller/base/controller.go
pkg/controller/host/controller.go

Reduce the retry time to 15 minutes to prevent DOS rejection.
While testing, noticed/fixed that `reQ` was not logging correctly.
https://bugzilla.redhat.com/show_bug.cgi?id=1953307

ReQ host connection failed 15 min to prevent DOS issues.

---

config/crds/forklift.konveyor.io_plans.yaml
config/forklift.konveyor.io_plans.yaml
pkg/apis/forklift/v1beta1/plan.go
pkg/apis/forklift/v1beta1/zz_generated.deepcopy.go
pkg/controller/plan/kubevirt.go
pkg/controller/plan/validation.go

When the `v1.multus-cni.io/default-network` annotation is set with the name of a network attachment definition, it looks for that NAD in `kube-system`, not in the pod's namespace as I previously thought. It's also valid in some circumstances to choose a NAD in a namespace outside of the pod's namespace. As such, the `transferNetwork` field on the Plan needs to be an object reference to properly identify the desired network.
This requires a corresponding change to the UI which I've already discussed with @mturley. 
https://github.com/k8snetworkplumbingwg/multus-cni/blob/a52680b3bfa026087879f89fae331b0dfc8dffe0/docs/configuration.md

Make TransferNetwork field an ObjectReference

---

pkg/controller/migration/controller.go

The list of VMs in the Migration CR's status is only updated while the Plan has the Executing condition, so VM status updates can get missed when the Plan is completed or canceled. This PR ensures that the list of VMs on the Migration is always up to date with the Plan.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1952362

reflectPlan should always sync the VM from the Plan status to the Migration

---

pkg/controller/plan/adapter/vsphere/builder.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/vm.go

In VMware, a template is a VM with a boolean property that says it is a template. The property is `config.template`.
Templates don't support warm migration, so we have decided to hide all the templates from the VM selection list in the UI.
This pull request does two things:
1. add a new field in the inventory: `IsTemplate` in the database, `isTemplate` is the JSON API response.
2. error out the templates in the VMImport builder, so that their migration is skipped.
Signed-off-by: Fabien Dupont <fdupont@redhat.com>

BZ 1957105 - Skip VMs that are actually templates

---

config/crds/forklift.konveyor.io_plans.yaml
config/forklift.konveyor.io_plans.yaml
pkg/apis/forklift/v1beta1/plan.go
pkg/apis/forklift/v1beta1/zz_generated.deepcopy.go
pkg/controller/plan/kubevirt.go

In the migration flow, the cutover date/time is set on the Migration CR by the user interface. We expect user to do the same through the API to keep a consistent flow. This means that the `cutover` field of the `Plan` is not needed anymore. Since we will soon release Forklift 2.0.0 with the API in v1beta1 version, it would be cleaner to do it soon, even if we add it back in the future.

Remove the cutover field from the Plan CRD

---

pkg/controller/plan/controller.go

Plans that completed successfully should not be able to be retried.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953145

Don't reconcile successful plans

---

pkg/controller/provider/container/ovirt/resource.go
pkg/controller/provider/model/base/model.go
pkg/controller/provider/model/base/tree.go
pkg/controller/provider/model/ocp/model.go
pkg/controller/provider/model/ovirt/model.go
pkg/controller/provider/model/ovirt/tree.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/model/vsphere/tree.go
pkg/controller/provider/web/base/tree.go
pkg/controller/provider/web/ovirt/cluster.go
pkg/controller/provider/web/ovirt/doc.go
pkg/controller/provider/web/ovirt/host.go
pkg/controller/provider/web/ovirt/network.go
pkg/controller/provider/web/ovirt/resource.go
pkg/controller/provider/web/ovirt/storage.go
pkg/controller/provider/web/ovirt/tree.go
pkg/controller/provider/web/ovirt/vm.go
pkg/controller/provider/web/ovirt/vnicprofile.go
pkg/controller/provider/web/ovirt/workload.go
pkg/controller/provider/web/vsphere/tree.go

Add tree & workload endpoints for oVirt.
There was a good bit of the vCenter tree code (and related model types) that could be shared. Refactored to `base` packages in both model and web layers.  Types moved to `base` (packages):
- Ref
- Tree
- TreeNode
- BranchNavigator
- ParentNavigator
- NodeBuilder (_new_)
The responsibility of fetching models while building the tree was shifted from the `Tree` to the the _navigator_.  This was necessary/better for 2 reasons:
1. For ovirt, the children need to be queried by parent ID.  Thus, the navigator already has the (child) models.  Returning `[]Ref` just to fetch 1-by-1 would be unnecessarily (very) inefficient.
2. The consolidation of concerns just makes since it's already navigating the model anyway.  This keeps knowledge of the model …

Add tree endpoint for oVirt.

---

pkg/controller/plan/validation.go

The refs in the Plan spec's `vms` field weren't being resolved properly due to the ref being a loop copy of the one on the plan, rather than the ref itself. This was causing VMs to not match the list of VMs in the Plan's copy of the migration status, which resulted in completed VMs being restarted.

Fix pointer issue w/ Plan VM ref resolution

---

pkg/controller/plan/validation.go

This fixes a pointer bug that was causing successful VMs to be remigrated.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1959731

BZ 1959731 - Fix pointer issue w/ Plan VM ref resolution

---

pkg/controller/plan/migration.go

Slice creation and assignment for kept VMs was happening inside of the for loop, so the slice of kept VMs would only ever have a single VM in it. Moved the creation and assignment outside of the loop to fix this.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953145
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1959731

Fix logic error w/ kept VMs in Migration.begin()

---

pkg/controller/plan/adapter/vsphere/builder.go
pkg/controller/plan/scheduler/vsphere/scheduler.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/base/tree.go
pkg/controller/provider/web/vsphere/cluster.go
pkg/controller/provider/web/vsphere/folder.go
pkg/controller/provider/web/vsphere/host.go
pkg/controller/provider/web/vsphere/tree.go
pkg/controller/provider/web/vsphere/vm.go
pkg/controller/provider/web/vsphere/workload.go

Update the algorithm for building the vSphere trees.  Results in a **5x** improvement in performance and (likely) reduced CPU usage.
**Instead of** traversing each node: following child refs and Get() each child by ref.  The number of queries is a multiple of the number of children of each node.  So 4k VMs results in 4k+ queries.
**The optimization** traverse each node: List() children by parent=_node_.  The number of queries is a multiple of the tree depth.
To achieve this:
- The vSphere `Model` objects needed a few _new_ _natural_ FK to parents.
- The tree _navigators_ needed to be rewritten (they are simple).
- The web resources updated to reflect the new FK fields (mainly to make visual testing easier).
- The existing` VM.Host` needed to be changed from type `Ref` to `string` to …

Optimized vSphere tree building.

---

pkg/controller/provider/container/vsphere/watch.go
pkg/controller/validation/policy/client.go
pkg/settings/policy.go

Fix (runaway) vsphere validation search.
The search lists VM that need to be validated in pages. However, the page was never incremented.  As a result, the loop would run _hot_ for a bit but would exit eventually when all of the VMs were validated.
However, the input queue to the validation worker queue has limited capacity and Pool.Submit() can return a `BacklogExceededError`.  This is anticipated and logged.  It's designed to be _best effort_ and relies on the next scheduled search to validate the VM.
However, there is a flaw that results in an infinite, _hot_ loop in the goroutine.
The _runaway_ scenario:
1. The VM created/updated event received.
2. The handler reports that it has scheduled the validation.
3. The Submit() fails and is logged.
4. The search lists VMs and finds the VM …

Fix vsphere validation search.

---

pkg/controller/provider/container/vsphere/watch.go
pkg/controller/validation/policy/client.go

Workload passed to the policy agent.  This eliminates the PA calling back to the provider API.
Note: Requires change in forklift-validation.

Workload passed to the policy agent.

---

go.mod
go.sum
pkg/controller/host/handler/vsphere/handler.go
pkg/controller/map/network/handler/ocp/handler.go
pkg/controller/map/network/handler/ovirt/handler.go
pkg/controller/map/network/handler/vsphere/handler.go
pkg/controller/map/storage/handler/ocp/handler.go
pkg/controller/map/storage/handler/ovirt/handler.go
pkg/controller/map/storage/handler/vsphere/handler.go
pkg/controller/plan/handler/ocp/handler.go
pkg/controller/plan/handler/ovirt/handler.go
pkg/controller/plan/handler/vsphere/handler.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/web/base/handler.go
pkg/controller/provider/web/client.go
pkg/controller/validation/policy/client.go
pkg/controller/watch/handler/handler.go
pkg/settings/policy.go

Better handling of provider inventory not-ready.
To distinguish between 404 because the provider has not yet been added to the container vs. the resource is not in the inventory, the client will:
- **Currently**: The client fetches the provider on every request.
- **This PR**: The web handler (server) sets the `X-Provider` header when the requested _provider_ is found in the container. If the header is not set, the client determines that the 404 is because the provider has not yet been loaded and returns a `ProviderNotReady` error.  Else, the provider is in the container but the resource is not found.
This enhancement will cut the number of GET requests to the API (from the controller) in half.
Also, noticed the `PartialContent` (206) was not being handled.
**Note**: Requires: …

Better handling of provider inventory not-ready.

---

pkg/controller/provider/web/base/handler.go
pkg/controller/provider/web/ovirt/client.go
pkg/controller/provider/web/ovirt/cluster.go
pkg/controller/provider/web/ovirt/datacenter.go
pkg/controller/provider/web/ovirt/disk.go
pkg/controller/provider/web/ovirt/diskprofile.go
pkg/controller/provider/web/ovirt/host.go
pkg/controller/provider/web/ovirt/network.go
pkg/controller/provider/web/ovirt/nicprofile.go
pkg/controller/provider/web/ovirt/provider.go
pkg/controller/provider/web/ovirt/storage.go
pkg/controller/provider/web/ovirt/tree.go
pkg/controller/provider/web/ovirt/vm.go
pkg/controller/provider/web/ovirt/workload.go

Refactor Handler.Link() for better separation of responsibility and re-use both inside and outside the web layer.
It's useful to Link and Expand REST resources outside the web layer.  It's complex and potentially dangerous to artificially build and use the _Handler_ because of unknown Handler state needs.
The main driver is to support the VM validation building the workload which needs to be a REST resource.
Essentially, functionality moved from endpoint _Handler_ to REST resources.
Summary:
- Removed Handler.Link().
- Added _Resource_.Link().
- Removed Handler.Build().
- Added _Resource_.Expand() to resources as necessary.  Here the term _expand_ refers to de-referencing foreign keys.
For consistency, we'll want to do the same refactor for vSphere.

Refactor Handler.Link() for better separation of responsibility and re-use outside the web layer.

---

pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/web/base/handler.go
pkg/controller/provider/web/ocp/client.go
pkg/controller/provider/web/ocp/namespace.go
pkg/controller/provider/web/ocp/netattachdefinition.go
pkg/controller/provider/web/ocp/provider.go
pkg/controller/provider/web/ocp/storageclass.go
pkg/controller/provider/web/ocp/vm.go
pkg/controller/provider/web/vsphere/client.go
pkg/controller/provider/web/vsphere/cluster.go
pkg/controller/provider/web/vsphere/datacenter.go
pkg/controller/provider/web/vsphere/datastore.go
pkg/controller/provider/web/vsphere/folder.go
pkg/controller/provider/web/vsphere/host.go
pkg/controller/provider/web/vsphere/network.go
pkg/controller/provider/web/vsphere/provider.go
pkg/controller/provider/web/vsphere/tree.go
pkg/controller/provider/web/vsphere/vm.go
pkg/controller/provider/web/vsphere/workload.go

The web `Handler`.Link() moved to _Resource_.Link() for both consistency and resource use outside of the web layer.
The `Workload` is used outside the web package for validation.  Deduplicated.
Fixes listing /providers endpoints broken in https://github.com/konveyor/forklift-controller/pull/274

Link() refactor in web layer.

---

pkg/controller/plan/adapter/ovirt/builder.go
pkg/controller/plan/adapter/ovirt/validator.go
pkg/controller/plan/scheduler/doc.go
pkg/controller/plan/scheduler/ovirt/scheduler.go
pkg/controller/provider/container/ovirt/client.go
pkg/controller/provider/container/ovirt/resource.go
pkg/controller/provider/model/ovirt/model.go
pkg/controller/provider/validation.go
pkg/controller/provider/web/ovirt/disk.go

* Adds ProvisionedSize field to the Disk
* Implements the oVirt builder. The secret requires a `cacert` field containing a b64 encoded root CA.
* Implements the oVirt scheduler. The scheduler will allow up to MaxInFlight VMs per provider to be running at once. We should probably have vSphere and oVirt have their own settings for the maximum number of transfers in flight, since vSphere is disks not VMs, and in any case limitations will be different per provider. This can be done in a follow up.

oVirt Builder and Scheduler

---

pkg/controller/plan/adapter/ovirt/adapter.go

The oVirt Builder wasn't having `Load()` called on it before, which meant the provisioner map was unpopulated and the destination storage would not have the correct volume and access modes set.

Load() the oVirt builder while constructing it

---

pkg/controller/provider/container/ovirt/model.go
pkg/controller/provider/container/ovirt/reconciler.go
pkg/controller/provider/web/ovirt/tree.go
pkg/controller/provider/web/ovirt/workload.go

oVirt part 7.
Renamed const to match [Event Documentation](https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/technical_reference/appe-event_codes).  A lot more event to follow in future PR.
Improved handling of the oVirt data reconciler lifecycle.
Updated oVirt trees.
Renamed the /tree/host to /tree/cluster since the tree really needs to be focused on the cluster.  Putting the VM under the host reflects an untrue containment relationship.
Tree:
- DataCenter
- Cluster
- VM
The `workload` has been flattened to match.
Workload:
- ID
- Name
- ...
- Host
- Cluster
- DataCenter

oVirt part 7

---

pkg/controller/plan/controller.go

Since we are always permitting retries in 2.1, this can be reverted.
Reverts konveyor/forklift-controller#259

Revert "Don't reconcile successful plans"

---

go.mod
go.sum
pkg/controller/provider/container/ovirt/model.go
pkg/controller/provider/model/base/model.go
pkg/controller/provider/model/ocp/model.go
pkg/controller/provider/model/ovirt/model.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/ocp/namespace.go
pkg/controller/provider/web/ocp/netattachdefinition.go
pkg/controller/provider/web/ocp/storageclass.go
pkg/controller/provider/web/ocp/vm.go
pkg/controller/provider/web/ovirt/tree.go
pkg/controller/provider/web/vsphere/tree.go

The `Model` interface related.  String(), Equals() and Labels() now optional.
Using `sql:incremented` instead of Created() and Updated() methods on the models.
Detail level=1 no longer means ALL.
The PK no longer blindly derived when not set.  As a result, the OCP primary key is the UID which is more straight forward anyway.
**Requires**: https://github.com/konveyor/controller/pull/82 expected to be released as 0.4.3.  Will update the PR when it's released.

controller 0.4.3 compat.

---

pkg/controller/provider/container/ovirt/model.go
pkg/controller/provider/container/ovirt/reconciler.go
pkg/controller/provider/container/ovirt/resource.go
pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/model/ovirt/model.go
pkg/controller/provider/web/ovirt/disk.go

Add additional _const_ for event codes.
Disk.StorageUsed renamed: `ActualSize` per RHV native naming.
A support for DataCenter events though don't know how to test it.  Not sure how to add/update/delete a DC.
Add support for vNICProfile events.  This uses the new container.Collection since these events do not indicate which profile changed.  A watch is added that will determine which VMs are affected and _tag_ them for re-validation.
This PR established this pattern.

Improved oVirt (change) detection and event handling.

---

pkg/controller/plan/adapter/vsphere/builder.go

Lets VMIO handle whether or not to start a VM during a warm migration. This permits it to use the VM's powerstate immediately before cutover to determine whether or not to start the destination VM. 
https://bugzilla.redhat.com/show_bug.cgi?id=1957791

Let VMIO manage VM start during warm migration

---

config/crds/forklift.konveyor.io_plans.yaml
config/forklift.konveyor.io_plans.yaml
pkg/apis/forklift/v1beta1/plan.go
pkg/controller/plan/handler/ocp/handler.go
pkg/controller/plan/kubevirt.go
pkg/controller/plan/validation.go

Plan.TargetNamespace() was falling back to the `Referenced` Plan's `Namespace` field. The `Referenced` Plan field is not populated for Plans, so this fails.

Fix Plan.TargetNamespace() nil pointer dereference

---

pkg/controller/provider/model/ovirt/model.go

Add `eq:"-"` tag to VM fields skipped in Equals() comparison performed by the `Collection` used by (RHV) change event handling.

Add eq:- tag to VM fields skipped in Equals() comparison.

---

pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/container/vsphere/watch.go

Fix updating VMs with batched validation result.  When something failed or the revision of the validated VM no longer matched the _latest_ VM, we needed to continue processing other task results instead of returning.  As a result, subsequent task results were not updating their VMs and VMs would remain un-validated (in the DB) until the next schedule validation or an update triggered (re)validation of the VM.
This is a regression introduced late in 2.0.0 performance/scale fixes that also affects vSphere.

Fix updating VMs with batched validation result.

---

pkg/controller/provider/container/ovirt/reconciler.go
pkg/controller/provider/container/ovirt/resource.go

Fix oVirt event refresh.
The algorithm of listing events sorted by date having noted the highest event ID is unnecessarily complex and flawed.
As a result - the reconciler was not determining the _latest_ event properly and processing _old_ events which caused a lot of NotFound errors applying the event.  The flaw was to sort by date.
Instead:
1. List events which are naturally sorted by `ID` descending.  This means a max=1 (limit) can be used to easily determine the latest event ID.
2. Note the `lastEvent` ID.
2. List events using the `from=lastEvent` parameter.
3. Sort (reverse) the list of events by ID ascending so they are applied in order created.
---
Example of failure.
```
{"level":"info","ts":1625083396.44058,"logger":"reconciler|ovirt","msg":"Event …
```

Fix oVirt event refresh.

---

pkg/controller/provider/web/ovirt/disk.go
pkg/controller/provider/web/ovirt/vm.go

Apparently the vNIC profile ref is optional. 
https://bugzilla.redhat.com/show_bug.cgi?id=1979652

vNIC profile optional in VM endpoint.

---

pkg/controller/provider/container/ovirt/resource.go

Fix oVirt cluster.name being overwritten with the description.
https://bugzilla.redhat.com/show_bug.cgi?id=1980353

Fix oVirt cluster.name.

---

pkg/controller/provider/container/ovirt/model.go
pkg/controller/provider/container/ovirt/reconciler.go
pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/validation/policy/client.go

Changes to support very large oVirt instances.
Listing all of the collections can be very slow so the we need to apply any events that occurred since we started before declaring parity and validating VMs.  This makes the state of the data collector (reconciler) more complex.  A _phases_ pattern seemed to fit. Also, since the RHV API is slow, we need a way to cancel all operations by passing the cancel _Context_ to the `Adapter`. 
Fetch VMs in pages.  This is needed to support not _crushing_ the RHV API and to cancel/abort faster.  The page size=100 is based on observed performance and seems like a good balance.  Does not seem to add much time to the overall duration yet provides somewhat timely cancel behavior.
Adjust logging level for - listing VMs to validate to level=3.

Support very large oVirt instances.

---

pkg/controller/provider/controller.go

The DB is locked while the provider data _collector_ is doing the initial load.  As a result, the controller worker is tied up until that finishes which prevents other CR events (like CR update/delete) from being dispatched.
The `Provider` does not need to be in the DB anyway.  The provider is fetched from the container.

Fix provider CR reconcile blocked on DB.

---

pkg/controller/provider/controller.go

The RHV data collector can be slow to shutdown.  In cases where a provider with the same name is deleted/added, there can be multiple DB clients open on the same DB file which may cause locking issues with sqlite3.
```
{"level":"info","ts":1626087031.6307125,"logger":"web|provider","msg":"","sql":"\nSELECT\nCOUNT(*)\nFROM
DataCenter\n;\n","params":null,"url":"/providers?detail=1","error":"database is locked","stacktrace ...
```

DB file path unique by provider name and UID.

---

pkg/controller/provider/container/vsphere/model.go

The vmware govmomi property collector URL-encodes object names.
https://bugzilla.redhat.com/show_bug.cgi?id=1953925

Un-URL-encode vSphere object names.

---

pkg/controller/provider/container/ovirt/model.go
pkg/controller/provider/container/ovirt/reconciler.go

Support both USER_ADD_VM(34) and USER_ADD_VM_STARTED(37) events.
There are two flows.
(A) With asynchronous tasks: First, USER_ADD_VM_STARTED is generated
(B) Without asynchronous tasks: First, USER_ADD_VM is generated
The disk and vNIC events follow.  Then, for asynchronous there a following:
USER_ADD_VM_FINISHED_SUCCESS or USER_ADD_VM_FINISHED_FAILURE (52).
We cannot simply rely on the USER_ADD_VM_FINISHED_SUCCESS create the VM because then, the update events for attaching disk and adding VMs will not find the VM in inventory to update (and fail).  So instead, the VM is created but then removed on USER_ADD_VM_FINISHED_FAILURE event.
https://bugzilla.redhat.com/show_bug.cgi?id=1982595

Handle user add VM (asynchronously).

---

pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/container/vsphere/reconciler.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/web/ovirt/vm.go
pkg/controller/validation/policy/client.go
pkg/settings/policy.go

As part of periodic listing VMs that need to be validated, the latest policy version is requested from the policy-agent (validation service).  The version for oVirt and vSphere are different but the path used by the controller in the URL was hard coded for /vmware/.  As a result, when getting the version intended to be match for oVirt (latest=1), it was the policy version for vSphere (latest-5).  This caused the query of:
```
where revision != revisionValidated OR policyVersion != :version
```
to always match ALL oVirt VMs becuase `:version` was incorrect for oVirt.
The fix is to pass the _endpoint_ for retrieving the version from the validation service like is done for validation.
https://bugzilla.redhat.com/show_bug.cgi?id=1985480
---
Also:
- adjusted the logging a little based on …

Fix excessive oVirt validation.

---

pkg/controller/provider/container/ovirt/model.go
pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/container/vsphere/watch.go

Fix processing RHV events for removal of (dataCenter, cluster, host & VM)
Event handler using `Ref` but should be using `ID` which results  in _model.NotFound_ error and leaving the object in the inventory.  This is especially bad for VMs because it results in 500 errors trying to expand them in the web API.
Also, log validation task error as log.Error() to include more context.
https://bugzilla.redhat.com/show_bug.cgi?id=1986106

Fix processing RHV events for removal.

---

Dockerfile

With #303 we removed `tar` from the image and this breaks the ability to copy files with `oc cp`. Since, `ubi8/ubi-micro` doesn't ship `tar` and doesn't allow to install it, we need to roll back to using `ubi8/ubi-minimal` and install `tar` during the image build.

Switch back to ubi8/ubi-minimal base image

---

pkg/apis/forklift/v1beta1/plan/vm.go
pkg/controller/plan/hook.go
pkg/controller/plan/migration.go

The division of role/responsibility got blurred a little between:`Migration.updateVM()` and `Migration.updatePipeline()`.
In the process, updateVM() made an assumption that when the VMIO import completed, the VM status should be marked as completed.  As a result, the following `PostHook` step will never run.
I _think_ the fix is to move parts of updateVM() that interpreted VMIO Import status to updatePipeline() which only updates the step in the pipeline and anything that involves updating VM overall succeeded/failed status is moved to Migration.Run().

Fix post hook not running.

---

go.mod
go.sum

Upgrade to gin 1.7.2 for CVE-2020-28483.
---
CVE-2020-28483
high severity
Vulnerable versions: < 1.7.0
Patched version: 1.7.0
This affects all versions of package github.com/gin-gonic/gin under 1.7.0. When gin is exposed directly to the internet, a client's IP can be spoofed by setting the X-Forwarded-For header.

Upgrade to gin 1.7.2 for CVE-2020-28483.

---

pkg/controller/provider/container/ovirt/client.go
pkg/controller/provider/container/ovirt/collector.go
pkg/controller/provider/container/ovirt/model.go
pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/web/ovirt/disk.go
pkg/controller/provider/web/ovirt/vm.go
pkg/controller/validation/policy/client.go

Fix disk creation not detected when cloned by template creation.
When a template is created the reference VMs disks are cloned (created).  As a result, we have VMs created with the template (thin provisioned) that references disks that are not in inventory. We need to refresh the disks when a template is created.  
It may seem _heavy-handed_ to fetch all of the disks but it's simpler than fetching the template and inspecting the disks.  Also, disk resources are relatively small resources and I doubt that template creation is a high volume event.
--- 
This PR also improves some logging.
---
This PR also address the latency between when events are generated and the current state of the RHV model.
For example, here is a list of events grabbed in a query:
- VM Created
- Disk attached.
- …

Fix disks not detected and created when clone by template creation.

---

pkg/controller/provider/container/vsphere/collector.go

By having a different "Folder -> childEntity" traversal from the "root" recursive traversal, the propertyFilter was not fully traversing a
vSphere tree recursively.  This was specifically preventing other objects such as datacenters and clusters that were nested in folders from being traversed to.
Steps to reproduce:
Run a govmomi vcsim with nested datacenters: `go/bin/vcsim -app 2 -cluster 4 -dc 4 -ds 8 -folder 32 -host 16 -nsx 2 -pg 4 -pg-nsx 2 -pod 2 -pool 8 -standalone-host 2 -vm 64`
Before:
```
{{} enter Folder:group-d1 [{{} name assign Datacenters}] []}
{{} enter Folder:group-2 [{{} name assign F0}] []}
{{} enter Folder:group-619 [{{} name assign F1}] []}
{{} enter Folder:group-1236 [{{} name assign F2}] []}
{{} enter Folder:group-1853 [{{} name assign F3}] []}
```
Note it doesn't …

Fix folder traversal spec not recursing fully

---

pkg/controller/provider/container/vsphere/collector.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/container/vsphere/watch.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/host.go

The `Host.VMs` list is very large and is updated whenever a VM is created,deleted.  As a result, when a VM is added and the list is updated, the controller re-validates all of the VMs on the host (because the host changed).
The `VM.Host` property (back-ref) provides that same linkage.

Removed Host.VMs property.

---

pkg/controller/provider/web/base/handler.go
pkg/controller/provider/web/client.go

Fix provider not ready detection for URL paths for resources _under a provider_.
The current approach:
When the provider is found (by server), a header X-Provider is set to the provider CR UID.
When the provider is not found (by server), returns a 404.  The client on 404 checks for the X-Provider header.  If found, determines the provider was found but the resource at the URL path is not found.
The flaw, is that an incorrect URL with result in a 404 and no X-Provider header and will be mistaken for ProviderNotFound.
The new approach:
Invert the logic.  When provider is not found (by server), still return 404 but sets an `X-Reason` reply header to _ProviderNotFound_.

Fix provider not ready detection.

---

go.mod
go.sum
pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/container/vsphere/watch.go

Using _transaction labels_ introduced in controller/v0.6.1, **ignore** _echo_ events generated when VMs are updated after they are validated.  Also, use buffered _input_ channel to add some _"slack"_.  Both prevent the VM model event handler from getting blocked on the first event during initial validation on provider startup.  For very large vCenter providers (node-5), I have seen watch queue overflow log entries:
"full queue, event discarded."
Log the "VM validated" at level: 3 which matches the default logging level when deployed by the operator.

VM validation event tuning and logging.

---

pkg/controller/provider/container/ovirt/resource.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/model/ovirt/model.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/ovirt/client.go
pkg/controller/provider/web/ovirt/cluster.go
pkg/controller/provider/web/ovirt/nicprofile.go
pkg/controller/provider/web/ovirt/vm.go

Makes oVirt Cluster resolvable by ref. Also adds the following inventory fields that will be needed by the VM and DataVolume builders.
oVirt:
- Cluster: BiosType
- VM: CpuThreads, SerialNumber
- NICProfile: Passthrough
vSphere:
- Disk: Key

Add inventory fields needed for single VM import

---

pkg/controller/host/validation.go
pkg/controller/provider/container/ovirt/resource.go
pkg/controller/provider/container/vsphere/collector.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/model/ovirt/model.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/ovirt/host.go
pkg/controller/provider/web/vsphere/host.go

Ensure host.Status on both vSphere and RHV host resources in the REST API.
Add a new Host CR validation to report the when a Host CR references a _real_ host that does not have a "green" status.
Also, changed the `InMaintenance` condition to be _Critical_ instead of _Warn_ because if the _real_ host is in maintenance or does not have a green status, we don't want to connect through the host for migration.

Add host.Status and new Host CR validation.

---

go.mod
go.sum
pkg/controller/provider/model/base/model.go
pkg/controller/provider/model/ovirt/model.go

When high-level (containing) entities such as DataCenter, StorageDomain and cluster are deleted, there are side effects in that all of the entities contained (owned) are silently deleted.
As a result, we need to mirror this behavior using non-enforced foreign keys.  The `fk` in the sql tag will automatically create an index.
Note: This is really hard to test in the wild because I don't have access to a real RHV provider that I can delete things like DataCenter, StorageDomain, Cluster etc.  So, I monkey-patched in the debugger and simulated it.

Cascading delete in oVirt model.

---

pkg/controller/plan/adapter/vsphere/builder.go
pkg/controller/provider/container/vsphere/collector.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/host.go

As with the oVirt builder PR, obsolete methods are temporarily left in to satisfy interfaces until the refactor/reimplementation is complete.

Add support for single VM import to vSphere builder

---

pkg/controller/plan/migration.go

Needs to head to StorePowerState after copying rather than CreateFinalSnapshot.

Fix warm migration finalization state transition

---

config/crds/forklift.konveyor.io_plans.yaml
config/forklift.konveyor.io_plans.yaml
pkg/apis/forklift/v1beta1/plan.go
pkg/controller/plan/adapter/base/doc.go
pkg/controller/plan/adapter/ovirt/builder.go
pkg/controller/plan/adapter/vsphere/builder.go
pkg/controller/plan/controller.go
pkg/controller/plan/handler/ovirt/handler.go
pkg/controller/plan/handler/vsphere/handler.go
pkg/controller/plan/kubevirt.go
pkg/controller/plan/migration.go
pkg/controller/plan/validation.go

Add support for archiving plans.
* Resources are now left behind when a migration fails. These resources are cleaned up when the Plan is retried, or when the Plan is archived. (Resources from canceled VMs are not retained)
* Setting the `archived` flag on the Plan causes all remaining resources (failed VMs, conversion and importer pods, configmaps, secrets, etc) to be cleaned up and the plan to get an `Archived` condition.
* kubevirt.go `Delete` methods now delete all left over resources for a plan rather than just those from a specific migration.
Misc
* Remove obsolete `RequiresConfigMap()` from Builder interface.

Archive plans

---

pkg/controller/plan/migration.go

Rather than always powering on the destination for warm migrations, defer to the power state of the source VM like cold migrations do.

Fix destination VM power on condition

---

pkg/controller/plan/kubevirt.go

Removing the Migration label from the label selector in `ListVMs` allows the VM CR map to be built when there is not an active migration.

Bug 2015940: Omit Migration label from List call when building the VM CR map

---

Makefile
pkg/controller/plan/adapter/ovirt/builder.go

The oVirt builder was not using the `detail=all` parameter when listing OCP VMs to build the mac conflict map, which was resulting in a null pointer issue due to the returned VMs not having their Object field populated. This fixes that issue by setting the correct detail level.
This change also adds a "debug" target to the Makefile to build the manager without optimizations so that the debugger works better.

Bug 2021622: oVirt builder: fix null ptr bug in macConflicts

---

pkg/controller/plan/adapter/base/doc.go
pkg/controller/plan/adapter/ovirt/client.go
pkg/controller/plan/adapter/vsphere/builder.go
pkg/controller/plan/adapter/vsphere/client.go
pkg/controller/plan/kubevirt.go
pkg/controller/plan/migration.go
pkg/settings/features.go

This adds support for the improved incremental backup process for VDDK in CDI, along with a feature gate to enable it. This feature allows vSphere snapshots to be cleaned up after each precopy, rather than having to wait to clean up at the end. In addition, this causes the snapshots to be removed when the plan is archived or a VM migration is canceled.

Bug 1942651: vSphere: pass changeID instead of snapshot to CDI

---

go.mod
go.sum
pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/container/vsphere/watch.go

Using _transaction labels_ introduced in controller/v0.6.1, **ignore** _echo_ events generated when VMs are updated after they are validated.  Also, use buffered _input_ channel to add some _"slack"_.  Both prevent the VM model event handler from getting blocked on the first event during initial validation on provider startup.  For very large vCenter providers (node-5), I have seen watch queue overflow log entries:
"full queue, event discarded."
Log the "VM validated" at level: 3 which matches the default logging level when deployed by the operator.
Signed-off-by: Fabien Dupont <fabiendupont@pm.me>

Bug 2027336: VM validation event tuning and logging.

---

pkg/controller/plan/adapter/vsphere/builder.go

Tightens up the backing file regex, and removes an unnecessary trim when populating a map from a list of existing datavolumes that could cause problems for VMs with hyphens and numbers at the end of their name.

Fix vSphere disk backing file name trimming

---

pkg/controller/provider/container/vsphere/collector.go

Fix (nil) client pointer passed to WaitForUpdatesEx().
The updateSet returned by WaitForUpdatesEx() can be nil when on TCP connection timeout.  Retry instead of reconnect in this part of the code.  If there is a connection issue, the subsequent WaitForUpdatesEx()  will error.  The SEGV was because the error returned by connect() was only logged with resulted in r.client being used when nil.

Bug 2024554: SEGV (nil) client pointer passed to methods.WaitForUpdatesEx().

---

pkg/controller/provider/container/ovirt/watch.go
pkg/controller/provider/container/vsphere/watch.go

The `0xfffc` non printable unicode character is making the build fail.
This pull request remove this character.
Note: I've built the `manager` binary and it compiles.

Remove non printable unicode character

---

pkg/controller/plan/adapter/ovirt/adapter.go
pkg/controller/plan/adapter/ovirt/builder.go
pkg/controller/plan/adapter/vsphere/builder.go

Stops setting the default volume and access modes in the datavolume builder, and instead only sets them if they were specified in the StorageMap. In all other cases the StorageProfile for the selected StorageClass will be used by CDI to determine the defaults.
Also removes some code related to Provisioners from the builders. The Provisioner API will still need to be removed in the future.

Let the StorageProfile decide volume/access modes

---

pkg/controller/provider/container/vsphere/collector.go
pkg/controller/provider/container/vsphere/model.go
pkg/controller/provider/model/vsphere/model.go
pkg/controller/provider/web/vsphere/cluster.go
pkg/controller/provider/web/vsphere/resource.go

Fix support for stand-alone Hosts.
A host system can be contained by any `ComputeResource`.  A cluster IsA  `ComputeResource`.  Standalone host will be contained by a `ComputeResource` (that is not a Cluster).
Both `ComputeResource` and `ClusterComputeResources` are stored in the model as `Cluster`.  However, the base `ComputeResource` containing stand-alone hosts are denoted using the `variant=ComputeResource` field.

Fix support for standalone host.

---

pkg/controller/plan/adapter/ovirt/builder.go
pkg/controller/plan/adapter/vsphere/builder.go
pkg/controller/provider/container/vsphere/model.go

* Don't overwrite the template spec if it exists.
* Do overwrite existing disks and volumes.
* Cause vSphere GuestID not to be wiped out
of inventory when the VM is powered off.

Fix OpenShift VM template processing

---

pkg/controller/plan/adapter/base/doc.go
pkg/controller/plan/adapter/ovirt/builder.go
pkg/controller/plan/adapter/ovirt/validator.go
pkg/controller/plan/adapter/vsphere/builder.go
pkg/controller/plan/adapter/vsphere/validator.go
pkg/controller/plan/validation.go

* Adds a validation to ensure that no more than one
nic is mapped to the pod network at a time.
* Create kubevirt nics for all source nics attached
to the same network.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2036208

Bug 2036208: Fix handling of multiple nics attached to same network

---

pkg/controller/plan/hook.go

Pre/Post migration hooks failed with wrong command arguments, updating job command arguments to make ansible runner working.
Works on my cluster now (preHook step passes in Forklift UI) and job pod log looks OK.
Before
```
...
ansible-runner: error: argument command: invalid choice: '/tmp/hook/playbook.yml' (choose from 'run', 'start', 'stop', 'is-alive', 'transmit', 'worker', 'process')
```
After
```
...
TASK [debug] *******************************************************************
ok: [localhost] => {
"msg": "testttt"
}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2053003

Fix Ansible Hook runner

---

pkg/controller/plan/hook.go

2.3 backport of https://github.com/konveyor/forklift-controller/pull/416
Pre/Post migration hooks failed with wrong command arguments with updated ansible runner, updating job
command arguments to make ansible runner working.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2053003

[BACKPORT] Fix Ansible Hook runner

---

pkg/controller/plan/hook.go

Pods created by Hook jobs should be persisted in order to allow access to their logs.
Disabling job pods restart and backofflimit.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2059333
The backofflimit = 0 doesn't create any new pod when the initial one has failed (if there was e.g. 2, the initial one and two other pods were created in case of simulated failure).
```plan1h``` job restartPolicy=never, backOffLimit=2 -> 3 pods on failure
```plan1h2``` job restartPolicy=never, backOffLimit=0 -> 1 pod on success, 1 pod on failure -> should be OK
```
$ oc get jobs -n openshift-mtv 
NAME                                COMPLETIONS   DURATION   AGE
plan1h-vm-3696-prehook-ztrjh        0/1           49m        49m
plan1h2-vm-3696-posthook-ltj9m      0/1           16m        16m …
```

Disable hook jobs restarts and keep their pods

---

pkg/controller/plan/hook.go

2.3 backport of https://github.com/konveyor/forklift-controller/pull/419
Pods created by Hook jobs should be persisted in order to allow access to their logs.
Disabling job pods restart and setting backOffLimit to 1.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2059333

[BACKPORT] Disable hook jobs restarts and keep their pods

---

pkg/controller/plan/adapter/ovirt/client.go

Fix a bug with multi-disk RHV warm imports, where every datavolume would be given the same disk snapshot ID for different disks (CDI has the same bug and accepts the import).
Found while investigating [RHBZ#2055201](https://bugzilla.redhat.com/show_bug.cgi?id=2055201), but not actually a complete fix.

Make sure snapshot disk ID matches target disk ID.

---

pkg/settings/features.go

Change the FEATURE_RETAIN_PRECOPY_IMPORTER_PODS default to true, to preserve importer pods in a warm migration. This workaround should not be needed anymore now that the bug in CDI has been fixed.

Default to retaining warm migration importer pods.

---

pkg/controller/plan/adapter/ovirt/builder.go

For [2087916](https://bugzilla.redhat.com/show_bug.cgi?id=2087916), choose the larger of ActualSize or ProvisionedSize so that CDI does not run out of space trying to download the snapshot. There are some cases where ActualSize can be larger.

Bug 2087916: Request oVirt DataVolume of ActualSize if larger than ProvisionedSize. 

---

pkg/controller/plan/adapter/ovirt/builder.go

2.3.2 backport of #429
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2087916

Backport to release-v2.3.2: Avoid failure downloading RHV snapshots.

---

pkg/settings/features.go

2.3.2 backport of #428
Fixes [BZ#2020304](https://bugzilla.redhat.com/show_bug.cgi?id=2020304)

Backport to release-v2.3.2: Default to retaining warm migration importer pods.

---

pkg/controller/plan/adapter/ovirt/client.go

"powering_down" status for VMs blocks snapshot removal, so it is likely more correct to wait just for "down" status

Do not consider powering off as down status for ovirt VM

---

pkg/controller/plan/migration.go

When importing a VM from ovirt provider the images (disks) don't require
conversion to kubevirt. The virt-v2v pod and execution should be skipped
to save time and resources.

Skip image conversion when importing from ovirt

---

pkg/controller/plan/adapter/ovirt/client.go

Setting the correlation id would allow us to see which migrationtriggered an action on oVirt and make it easier to debug.
Example:
```
2022-07-11 17:28:16,138+03 INFO  [org.ovirt.engine.core.bll.snapshots.CreateSnapshotForVmCommand] (default task-116) [copy-of-plan-1657549684863] Lock Acquired to object 'EngineLock:{exclusiveLocks='[27bc786a-f52b-4f3b-b3da-25a4dced467d=VM]', sharedLocks=''}'
```

Add correlation id to oVirt provider requests

---

Makefile

Modifying Makefile, with current implementation for newer go version controller-gen is not being installed properly and the build failed, changing "go get" to "go install" and removing the temp dir since it's not required, the binary file is placed under $HOME/go/bin. 
Also changing controller-gen to a newer version (still support legacy features) and switching docker with podman.

NO ISSUE: Modifying Makefile

---

Makefile

Issue: when running the controller locally it would throw this exception
```
multiple group-version-kinds associated with type *v1.VirtualMachineList, refusing to guess at one'","stacktrace":"\ngithub.com/konveyor/forklift-controller/pkg/controller/provider/container/ocp.(*VM).Reconcile()\n\t/home/mnecas/Desktop/Projects/Redhat/forklift/forklift-controller/pkg/controller/provider/container/ocp/collection.go:351\ngithub.com/konveyor/controller/pkg/inventory/container/ocp.(*Collector).reconcileCollections()\n\t/home/mnecas/go/pkg/mod/github.com/konveyor/controller@v0.10.0/pkg/inventory/container/ocp/collector.go:231\ngithub.com/konveyor/controller/pkg/inventory/container/ocp.(*Collector).start()\n\t/home/mnecas/go/pkg/mod/github.com/konveyor/controller@v0.10.0/pkg/inventory/container/ocp/col …
```

Add KUBEVIRT_CLIENT_GO_SCHEME_REGISTRATION_VERSION=v1 to make run

---

Makefile

Add podman to makefile
When both are available the docker will be used over podman to not break backward compatibility.

Add podman to makefile

---

pkg/controller/plan/adapter/ovirt/builder.go

the user may not have virtio drivers for windows guests, it's better to convert them to SATA instead

VM mapping: map IDE to Sata

---

pkg/controller/plan/adapter/ovirt/builder.go

Currently, when migrating the VM the network interface has always Virtio.
This patch uses the interface which was used in the provider.
https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/

VM mapping: Add dynamic nic interface

---

pkg/controller/plan/adapter/ovirt/client.go
pkg/controller/provider/container/ovirt/client.go
pkg/controller/provider/validation.go

Issue:
We would like to add a "Verify server's SSL certificate" field to the forklift UI, as suggested here: https://github.com/konveyor/forklift-ui/pull/977#issuecomment-1206617874
In some cases it's beneficial for users who do not need this extra security to skip the SSL verification. 
Suggestion:
Add a new `insecureSkipVerify` flag to the oVIrt connection secret to allow insecure connection for oVirt servers.
If this flag is set to `true`, `cacert` field is ignored and an insecure connection is created.
Ref: https://github.com/konveyor/forklift-ui/pull/977
Signed-off-by: yzamir <yzamir@redhat.com>

MTV-337: Allow insecure connection to Ovirt server

---

pkg/controller/plan/adapter/base/doc.go
pkg/controller/plan/adapter/ovirt/client.go
pkg/controller/plan/adapter/vsphere/client.go
pkg/controller/plan/migration.go

Bug [2055201](https://bugzilla.redhat.com/show_bug.cgi?id=2055201) shows frequent importer pod restarts for warm migrations from oVirt, and one of the reasons given by the oVirt API is "Cannot transfer Virtual Disk. Snapshot is currently being created for VM".
It should be easy enough to clean up these restarts by having the forklift controller wait for the snapshot to be marked ready, but I'm not sure if I have the right approach in this pull request? I have marked it a draft in case adding to the state machine isn't really the right thing to do, and because the VMware part isn't really filled out (although VMware doesn't seem to have the same problem).

Bug 2055201: Avoid starting importer before snapshots are ready to transfer.

---

pkg/controller/plan/kubevirt.go
pkg/controller/plan/migration.go

The format of the importer pod name has changed recently, but fortunately for us CDI applies an annotation to the PVC which identifies the pod. This changes GetImporterPod to read the pod name from that annotation.

GetImporterPod: Get pod name from PVC annotation

---

pkg/controller/plan/kubevirt.go

With the new CDI change, the data volumes being deleted when the import completes. However, the controller lookup for the data volumes in order to know when the disk transfer is complete and and progress with the migration flow. In order to prevent it, an annotation is added to the data volumes.

Prevent data volume deletion
