kubev2v/forklift-controller

- pkg/controller/provider/vmware/adapter.go
- pkg/controller/provider/vmware/reconciler.go
Missed vRef and vRefList two when renaming things.
> Minor renaming.

- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/model/base/model.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/cluster.go
- pkg/controller/provider/web/vsphere/datacenter.go
- pkg/controller/provider/web/vsphere/datastore.go
- pkg/controller/provider/web/vsphere/folder.go
- pkg/controller/provider/web/vsphere/host.go
- pkg/controller/provider/web/vsphere/network.go
- pkg/controller/provider/web/vsphere/tree.go
- pkg/controller/provider/web/vsphere/vm.go
- vendor/github.com/konveyor/controller/pkg/inventory/container/container.go
- vendor/github.com/konveyor/controller/pkg/inventory/container/doc.go
- vendor/github.com/konveyor/controller/pkg/inventory/model/client.go
- vendor/github.com/konveyor/controller/pkg/inventory/model/doc.go
- vendor/github.com/konveyor/controller/pkg/inventory/model/journal.go
- vendor/github.com/konveyor/controller/pkg/inventory/model/label.go
- vendor/github.com/konveyor/controller/pkg/inventory/model/model.go
- vendor/github.com/konveyor/controller/pkg/inventory/model/model_test.go
- vendor/github.com/konveyor/controller/pkg/inventory/model/predicate.go
- vendor/github.com/konveyor/controller/pkg/inventory/model/table.go
Leverage with latest _libmodel_ enhancements [pull/15](https://github.com/konveyor/controller/pull/15).
- Simplified `db.List()`.
- Use _builtin_ `bool` field types. 
- Use `db.GetForUpdate()`.
> Latest libmodel enhancements.

- pkg/controller/controller.go
- pkg/controller/provider/controller.go
- pkg/settings/inventory.go
- pkg/settings/role.go
- pkg/settings/settings.go
Add role, inventory settings and use them.
Most of this code taken directly from mig-controller.
> Add role, inventory settings and use them.

- pkg/controller/provider/container/vsphere/reconciler.go
Fix detection of initial batch of updates and set the `consistent` flag.  The `Truncated` field is `nil` unless a _MaxObjectUpdates_ is set.
Added some logging.
> Fix vSphere consistency detection and add logging.

- pkg/controller/plan/validation.go
- pkg/controller/provider/web/base/client.go
- pkg/controller/provider/web/client.go
- pkg/controller/provider/web/ocp/client.go
- pkg/controller/provider/web/vsphere/client.go
Small improvement to the client.
> Web client improvements.

- config/crds/virt_v1alpha1_provider.yaml
- config/samples/provider.yaml
- pkg/apis/virt/v1alpha1/provider.go
- pkg/controller/provider/controller.go
- pkg/controller/provider/validation.go
- pkg/controller/provider/web/ocp/provider.go
Add support for a _host_ provider which has a blank URL and secret ref.
Fixes /providers (list) endpoint for openshift providers.
> Support host provider.

- pkg/controller/host/controller.go
- pkg/controller/map/network/controller.go
- pkg/controller/map/storage/controller.go
- pkg/controller/migration/controller.go
- pkg/controller/migration/migrate.go
- pkg/controller/plan/controller.go
- pkg/controller/provider/container/ocp/collection.go
- pkg/controller/provider/container/ocp/reconciler.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/controller.go
- vendor/github.com/konveyor/controller/pkg/inventory/container/container.go
- vendor/github.com/konveyor/controller/pkg/inventory/container/ocp/collection.go
- vendor/github.com/konveyor/controller/pkg/inventory/container/ocp/doc.go
- vendor/github.com/konveyor/controller/pkg/inventory/container/ocp/reconciler.go
This PR mainly improves lifecycle and error handling/recovery for provider (data) reconcilers.
While doing this, I noticed an opportunity to improve the controller `Reconciler` design pattern regarding event requeue.
requires: https://github.com/konveyor/controller/pull/23
> Improved error handling and recovery in data reconcilers.

- config/crds/virt_v1alpha1_migration.yaml
- pkg/apis/virt/v1alpha1/migration.go
- pkg/apis/virt/v1alpha1/plan.go
- pkg/apis/virt/v1alpha1/snapshot.go
- pkg/apis/virt/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/migration/controller.go
- pkg/controller/migration/migrate.go
- pkg/controller/migration/validation.go
- pkg/controller/plan/controller.go
- pkg/controller/plan/validation.go
Snapshot resources referenced in the plan and migration CRs. The snapshot for each is stored in an associated `ConfigMap`.  Added Started, Completed timestamps in the MigrationStatus.  Generally useful be especially useful to determine if the migration had started and the snapshot should be frozen.
> Snapshot referenced resources.

- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/vm.go
The cpu affinity should be a []int32.
> Fix cpu affinity.

- pkg/controller/provider/container/vsphere/reconciler.go
When I added transaction to Reconciler.getUpdates(), I broke things.
Updates used in `GetForUpdate()` while already in a transaction causes a deadlock because` GetForUpdate() `creates a transaction (under the covers) as well.  Go does not support re-entrant locks.
Added _defer_ to ensure transaction not leaked and DB locked forever.
Propagate the error back up to the main loop.  Not propagating errors is a leftover from the initial prototype.  I think it makes sense for the entire update to be applied and committed or fail atomically.
> Fix vsphere updates; improved error and DB transaction management.

- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/vm.go
Add Networks and Concerns to VM REST resource.
The _concerns_ will eventually be populated by integration with MA shared validation service.
> Add Networks and Concerns to VM REST resource.

- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
Add virtual disk capacity.
```
"disks": [
{
"file": "[NFS_Datastore] jortel-test/jortel-test.vmdk",
"datastore": {
"Kind": "Datastore",
"ID": "datastore-35"
},
"capacity": 17179869184
}
],
```
> Add virtual disk capacity.

- pkg/controller/plan/builder/vsphere/builder.go
- pkg/controller/plan/kubevirt.go
Fixes for migration without host SEGV and with multiple VMs.
> Migration fixes.

- pkg/controller/plan/builder/vsphere/builder.go
Build a URL using `Host.Spec.IpAddress` when found.
Building a URL instead of passing the IP, else, migration failed by VMIO with invalid scheme which I think is reported by `govmomi`.
> Fix secret host URL.

- pkg/controller/plan/migration.go
Get the destination provider secret and build a new client only when not the _host_ provider.
The `Migration.destination.secret` not used/needed.   removed.
> Fix migration to host: secret not found.

- config/crds/virt_v1alpha1_plan.yaml
- pkg/apis/virt/v1alpha1/plan/vm.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
Add _optional_ name per VM on the plan..  This overrides the source VM name.
> Add optional plan VM name.

- pkg/controller/provider/controller.go
- pkg/controller/provider/web/base/client.go
- pkg/settings/inventory.go
- vendor/github.com/konveyor/controller/pkg/inventory/web/web.go
Add host and port settings for the inventory service.
Requires: https://github.com/konveyor/controller/pull/30
> Add host and port settings.

- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/model/vsphere/doc.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/host.go
- pkg/controller/provider/web/vsphere/provider.go
- pkg/controller/provider/web/vsphere/vm.go
Add additional inventory properties.
closes #73
> Provider inv 9

- config/crds/virt_v1alpha1_host.yaml
- config/crds/virt_v1alpha1_migration.yaml
- config/crds/virt_v1alpha1_plan.yaml
- pkg/apis/virt/v1alpha1/host.go
- pkg/apis/virt/v1alpha1/plan/migration.go
- pkg/controller/plan/migration.go
Add `Description` to pipeline steps.
> Add Step description

- .gitignore
- .travis.yml
- pkg/apis/virt/v1alpha1/resource_test.go
Travis and Codecov applications are already enabled for the Konveyor organization.
This pull request creates a Travis configuration file that runs Codecov on the project.
> Activate Travis and Codecov to the repository

- pkg/apis/virt/v1alpha1/provider.go
- pkg/controller/provider/container/ocp/reconciler.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/controller.go
- pkg/controller/provider/validation.go
- vendor/github.com/konveyor/controller/pkg/condition/condition.go
- vendor/github.com/konveyor/controller/pkg/inventory/container/container.go
Add provider connection test, additional conditions and events.
The `ConnectionTested` and `InventoryCreated` conditions are _required_ for the `Ready` condition.
```
Status:
Conditions:
Category:              Required
Last Transition Time:  2020-11-24T00:05:53Z
Message:               Connection test, succeeded.
Reason:                Tested
Status:                True
Type:                  ConnectionTested
Category:              Advisory
Last Transition Time:  2020-11-24T00:05:53Z
Message:               Validation has been completed.
Reason:                Completed
Status:                True
Type:                  Validated
Category:              Required
Last Transition Time:  2020-11-24T00:06:04Z
Message:               The inventory has been loaded.
Reason:                Completed …
```
> Add provider connection test.

- pkg/controller/provider/web/vsphere/vm.go
This PR fixes a typo in the JSON inventory API for CPU Hot Add/Remove feature.
> Fix cpuHot{Add,Remove}Enabled typo

- config/crds/forklift_v1alpha1_host.yaml
- pkg/apis/forklift/v1alpha1/host.go
- pkg/apis/forklift/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/host/controller.go
- pkg/controller/host/validation.go
- pkg/controller/plan/builder/vsphere/builder.go
- pkg/controller/plan/builder/vsphere/host.go
Improved host validation; connection check; add events.
Make secret required.
```
Status:
Conditions:
Category:              Advisory
Last Transition Time:  2020-12-09T21:23:33Z
Message:               The host has been validated.
Status:                True
Type:                  Validated
Category:              Required
Last Transition Time:  2020-12-09T21:23:33Z
Message:               Connection test, succeeded.
Reason:                Tested
Status:                True
Type:                  ConnectionTested
Category:              Required
Last Transition Time:  2020-12-09T21:23:33Z
Message:               The host is ready.
Status:                True
Type:                  Ready
Observed Generation:     1
Events:
Type    Reason            Age   From  Message
----    ------ …
```
> Host validation; add connection check and events.

- pkg/controller/plan/controller.go
- pkg/controller/plan/validation.go
Add host validation.  Important to ensure that Host CRs in the same namespace as the source provider is `Ready`.
Emit events for conditions.
```
Status:
Conditions:
Category:              Required
Last Transition Time:  2020-12-10T00:01:22Z
Message:               The migration plan is ready.
Status:                True
Type:                  Ready
Category:              Advisory
Durable:               true
Last Transition Time:  2020-12-10T00:02:14Z
Message:               The plan is EXECUTING.
Status:                True
Type:                  Executing
Observed Generation:  1
Events:
Type    Reason     Age               From  Message
----    ------     ----              ----  -------
Normal  Ready      3s (x6 over 1m)   plan  The migration plan is ready.
Normal  Executing  3s (x4 over …
```
> Plan validation: Add host validation; events.

- pkg/controller/provider/controller.go
Fix provider API: provider conditions not updated (in theAPI).
The endpoint handler uses the container (not the DB) to inventory providers.  The container is only updated when the `Spec` changes.  The fix is to unconditionally update the container at the end of each reconcile.
fixes #113
> Fix provider API: provider conditions not updated (in theAPI).

- pkg/controller/host/validation.go
- pkg/controller/provider/controller.go
Fix host compile error introduced by merge.
Also, fix const/type mismatch noted in review but not corrected before PR merge.
> Fix host compile error introduced by merge.

- config/crds/forklift_v1alpha1_networkmap.yaml
- config/crds/forklift_v1alpha1_plan.yaml
- pkg/apis/forklift/v1alpha1/mapped/network.go
- pkg/controller/validation/network.go
Replace type validation check in network validation with CRD enumeration (marker).
Include the list of networks not found in condition.
> Enumerate network type; include networks not found list.

- pkg/controller/plan/builder/vsphere/host.go
- pkg/controller/provider/container/vsphere/reconciler.go
Secure connect using the thumbprint.
fixes #124
> vSphere secure connect with thumbprint.

- pkg/controller/plan/builder/vsphere/builder.go
- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/vm.go
Inventory VM powerState and propagate to VM Import CR (StartVM).
closes #123
> Add VM powerState to inventory; set VMIO startVM based on it.

- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
Set VMIO secret owner reference to the corresponding VirtualMachineImport CR.
https://bugzilla.redhat.com/show_bug.cgi?id=1900345
> Set VMIO secret owner reference.

- pkg/controller/plan/controller.go
The plan needs to reconciled after _other_ CRs to ensure it's validation is evaluating the reconciled CRs.  This is mainly needed at controller startup.
Follow on to: https://github.com/konveyor/forklift-controller/pull/136
> Ensure CR reconciliation order.

- pkg/controller/plan/controller.go
Fix plan postpone using wrong lists.
> Fix plan postpone.

- pkg/controller/plan/validation.go
Validate VM name is legal for k8s.
Related to: [bug: 1900353](https://bugzilla.redhat.com/show_bug.cgi?id=1900353)
> Validate VM name is legal for k8s.

- cmd/manager/main.go
- go.mod
- go.sum
- pkg/apis/forklift/v1alpha1/plan.go
- pkg/controller/plan/context/migration.go
- pkg/controller/plan/controller.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
- pkg/controller/plan/validation.go
- pkg/controller/provider/container/ocp/collection.go
- pkg/controller/provider/container/ocp/reconciler.go
- pkg/controller/provider/model/ocp/doc.go
- pkg/controller/provider/model/ocp/model.go
- pkg/controller/provider/web/ocp/client.go
- pkg/controller/provider/web/ocp/doc.go
- pkg/controller/provider/web/ocp/vm.go
https://bugzilla.redhat.com/show_bug.cgi?id=1897284
Add plan validation of VM.  Ensure a VM with the same name does not already exist in the _target_ namespace on the destination.
Summary:
- add `VirtualMachine` to the openshift provider inventory.
- add plan validation.
> Bug 1897284: Validate target VM does not already exist.

- pkg/controller/provider/container/ocp/reconciler.go
Fix OCP provider connection test.
Requires https://github.com/konveyor/controller/pull/47
Fixes #151
> Fix OCP provider connection test.

- go.mod
- go.sum
- pkg/controller/provider/container/ocp/reconciler.go
Required for: https://github.com/konveyor/forklift-controller/pull/153
> controller (lib) 0.2.8.

- pkg/controller/plan/builder/vsphere/builder.go
Fix selecting incorrect host IP.
https://bugzilla.redhat.com/show_bug.cgi?id=1927838
> Fix bug: 1927838 re: selecting incorrect host IP.

- config/crds/forklift.konveyor.io_migrations.yaml
- config/crds/forklift.konveyor.io_plans.yaml
- config/forklift.konveyor.io_migrations.yaml
- config/forklift.konveyor.io_plans.yaml
Regenerate CRDs to allow nil conditions.
> Regenerate CRDs

- pkg/controller/plan/controller.go
- pkg/controller/plan/migration.go
This fixes a few things I didn't get quite right when switching the way the conditions are reflected.
* Finish staging conditions on the snapshot before cloning them to the plan.
* Fix erroneous usage of `HasCondition` where `HasAnyCondition` was needed.
* Remove any conditions from the plan that aren't on the snapshot.
* Set the `Executing` condition on the active snapshot instead of the plan.
> Fix condition flow between plan and snapshot

- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/model/vsphere/doc.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/cluster.go
- pkg/controller/provider/web/vsphere/host.go
- pkg/controller/provider/web/vsphere/network.go
Add (missing) Cluster.Hosts and include DvSwitch in /networks model & endpoint.
Add `variant` to the Network model and REST resource.
> Provider API: Add Cluster.Hosts and include DvSwitch in /networks endpoint.

- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/host.go
Add host subnetMask; managementServerIp.
closes #120
> Add host subnetMask; managementServerIp.

- config/crds/forklift.konveyor.io_hosts.yaml
- config/crds/forklift.konveyor.io_migrations.yaml
- config/crds/forklift.konveyor.io_networkmaps.yaml
- config/crds/forklift.konveyor.io_plans.yaml
- config/crds/forklift.konveyor.io_providers.yaml
- config/crds/forklift.konveyor.io_storagemaps.yaml
- config/forklift.konveyor.io_hosts.yaml
- config/forklift.konveyor.io_migrations.yaml
- config/forklift.konveyor.io_networkmaps.yaml
- config/forklift.konveyor.io_plans.yaml
- config/forklift.konveyor.io_providers.yaml
- config/forklift.konveyor.io_storagemaps.yaml
- pkg/apis/forklift/v1alpha1/host.go
- pkg/apis/forklift/v1alpha1/mapping.go
- pkg/apis/forklift/v1alpha1/migration.go
- pkg/apis/forklift/v1alpha1/plan.go
- pkg/apis/forklift/v1alpha1/provider.go
- pkg/controller/map/network/controller.go
- pkg/controller/map/storage/controller.go
Add CRD list column headings.
```
[jortel@f28a virt][AWS4]$ oc get provider
NAME      TYPE        READY     CONNECTED   INVENTORY   URL                                                  AGE
boston    vsphere     True      True        True        https://vcenter.v2v.bos.redhat.com/sdk               43m
host      openshift             True                                                                         43m
psi4      openshift   True      True        True        https://api.cluster-jortel.v2v.bos.redhat.com:6443   43m
[jortel@f28a virt][AWS4]$ oc get hook
NAME      READY     IMAGE                          AGE
custom              quay.io/jmontleon/wait         30m
test                quay.io/konveyor/hook-runner   30m
[jortel@f28a virt][AWS4]$ oc get plan
NAME      READY     EXECUTING …
```
> Add CRD column headings.

- config/crds/forklift.konveyor.io_plans.yaml
- config/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1alpha1/plan.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/validation.go
Adds a field to the Plan CR to permit choosing a transfer network. I'm not thrilled about any of the names I came up with, so open to suggestions.
> Transfer network selection

- config/samples/hook.yaml
Add comment that shows the playbook.
This also helps document the plan.yml and workload.yml files available to the playbook.
> Improved sample hook.

- pkg/controller/plan/kubevirt.go
Realized that even though the pipeline `CreateImport` phase will only create the import once, the warm migration logic needs to be able to update the cutover.  To support updating the VMIO import CR, the KubeVirt.EnsureImport() really needs to update _found_ VMIO resources.
> Update found vmio resources.

- pkg/controller/plan/migration.go
This causes the VMI CRs to be updated on each reconcile after the import has started, so that a change to the
warm migration cutover can be picked up and applied.
> Call EnsureImport during the ImportCreated phase

- config/crds/forklift.konveyor.io_hosts.yaml
- config/crds/forklift.konveyor.io_providers.yaml
- config/forklift.konveyor.io_hosts.yaml
- config/forklift.konveyor.io_providers.yaml
- pkg/apis/forklift/v1alpha1/host.go
- pkg/apis/forklift/v1alpha1/provider.go
- pkg/controller/host/controller.go
- pkg/controller/host/validation.go
- pkg/controller/provider/controller.go
- pkg/controller/provider/validation.go
Explicit connection test conditions for succeeded and failed.
Simpler for UI to display.
> Explicit connection test conditions: succeeded/failed.

- pkg/controller/plan/kubevirt.go
The VMI CRs are currently getting updated on every reconcile, which is the likely cause of https://bugzilla.redhat.com/show_bug.cgi?id=1940694. This PR replaces that update with a PATCH, and only if the cutover date has changed. This should clear up the resource conflicts.
> Only PATCH the vmimport cutover if it's been changed

- go.mod
- go.sum
> Fix TLS for wss watch websocket.

- Makefile
- config/crds/forklift.konveyor.io_hooks.yaml
- config/crds/forklift.konveyor.io_hosts.yaml
- config/crds/forklift.konveyor.io_migrations.yaml
- config/crds/forklift.konveyor.io_networkmaps.yaml
- config/crds/forklift.konveyor.io_plans.yaml
- config/crds/forklift.konveyor.io_providers.yaml
- config/crds/forklift.konveyor.io_provisioners.yaml
- config/crds/forklift.konveyor.io_storagemaps.yaml
- config/forklift.konveyor.io_hooks.yaml
- config/forklift.konveyor.io_hosts.yaml
- config/forklift.konveyor.io_migrations.yaml
- config/forklift.konveyor.io_networkmaps.yaml
- config/forklift.konveyor.io_plans.yaml
- config/forklift.konveyor.io_providers.yaml
- config/forklift.konveyor.io_provisioners.yaml
- config/forklift.konveyor.io_storagemaps.yaml
> Generate v1 CRDs.

- pkg/controller/plan/validation.go
https://bugzilla.redhat.com/show_bug.cgi?id=1923031
> Use IsDNS1123Label to validate VM names

- config/samples/host.yaml
> Fix typo in Host CR sample

- pkg/controller/plan/builder/vsphere/builder.go
- pkg/controller/plan/builder/vsphere/host.go
- pkg/controller/plan/kubevirt.go
Fixes https://github.com/konveyor/forklift-controller/issues/214
> Fix up Builder and Kubevirt error wrapping

- README.md
- cmd/manager/main.go
- go.mod
- go.sum
- pkg/controller/hook/controller.go
- pkg/controller/host/controller.go
- pkg/controller/host/handler/vsphere/handler.go
- pkg/controller/map/network/controller.go
- pkg/controller/map/network/handler/ocp/handler.go
- pkg/controller/map/network/handler/vsphere/handler.go
- pkg/controller/map/storage/controller.go
- pkg/controller/map/storage/handler/ocp/handler.go
- pkg/controller/map/storage/handler/vsphere/handler.go
- pkg/controller/migration/controller.go
- pkg/controller/plan/context/migration.go
- pkg/controller/plan/controller.go
- pkg/controller/plan/handler/ocp/handler.go
- pkg/controller/plan/handler/vsphere/handler.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
- pkg/controller/plan/scheduler/vsphere/scheduler.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/container/vsphere/watch.go
- pkg/controller/provider/controller.go
- pkg/controller/validation/policy/client.go
- pkg/settings/logging.go
- pkg/settings/profiler.go
- pkg/settings/settings.go
Add a ton on logging statements.  See README.md for details.
> Additional logging.

- pkg/controller/plan/builder/vsphere/host.go
- pkg/controller/provider/container/vsphere/reconciler.go
Ensure vsphere & esx host connections are completely closed.
> Ensure vsphere & esx host connections are completely closed.

- config/crds/forklift.konveyor.io_migrations.yaml
- config/crds/forklift.konveyor.io_plans.yaml
- config/forklift.konveyor.io_migrations.yaml
- config/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1alpha1/plan/migration.go
- pkg/controller/plan/migration.go
- pkg/controller/plan/validation.go
* Make VM status reflect the VMI Pending condition
* If a DV hasn't bound yet, reflect the reason why in the DiskTransfer step's phase.
> VM should reflect Pending condition from VM import

- pkg/controller/host/handler/vsphere/handler.go
- pkg/controller/map/network/handler/ocp/handler.go
- pkg/controller/map/network/handler/vsphere/handler.go
- pkg/controller/map/storage/handler/ocp/handler.go
- pkg/controller/map/storage/handler/vsphere/handler.go
- pkg/controller/plan/handler/ocp/handler.go
- pkg/controller/plan/handler/vsphere/handler.go
Fix inventory handler queueing with multiple matches.
> Fix inv handler queueing with multiple matches.

- pkg/controller/plan/hook.go
- pkg/controller/plan/migration.go
Re-add hook phases accidental removed in earlier PR.
> Re-add hook phases.

- pkg/controller/migration/controller.go
> BZ 1952362 - reflectPlan should always sync the VMs (#247)

- pkg/controller/plan/scheduler/vsphere/scheduler.go
The scheduler should ignore Plans that aren't running, and it shouldn't bother looking up a VM in the inventory unless that VM is being migrated. For safety's sake VMs that can't be found in the inventory are also ignored.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1956467
> Scheduler improvements

- pkg/controller/plan/scheduler/vsphere/scheduler.go
> BZ 1956467 - Scheduler improvements

- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/container/vsphere/reconciler.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/vm.go
> BZ 1957105 - Skip VMs that are actually templates (#252)

- pkg/controller/plan/migration.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1957877
> Reset Warm status when restarting a migration

- config/crds/forklift.konveyor.io_plans.yaml
- config/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/apis/forklift/v1beta1/zz_generated.deepcopy.go
- pkg/controller/plan/kubevirt.go
> Remove the cutover field from the Plan CRD

- go.mod
- go.sum
- pkg/controller/host/predicate.go
- pkg/controller/map/network/predicate.go
- pkg/controller/map/storage/predicate.go
- pkg/controller/migration/predicate.go
- pkg/controller/plan/predicate.go
- pkg/controller/provider/container/ovirt/resource.go
- pkg/controller/provider/container/vsphere/watch.go
- pkg/controller/provider/controller.go
- pkg/controller/provider/model/ovirt/model.go
- pkg/controller/provider/web/ovirt/vm.go
- pkg/controller/validation/policy/client.go
- pkg/controller/watch/handler/watch.go
- pkg/settings/policy.go
General hardening and memory leak fixes.
> General hardening and memory leak fixes.

- pkg/controller/provider/container/vsphere/watch.go
- pkg/controller/provider/controller.go
- pkg/controller/validation/policy/client.go
- pkg/settings/policy.go
Revised policy agent (validation service) integration.
- Provides concurrency (and throttling) limit across all providers using a shared worker pool.
- Batch updating VM with validated result into into transactions.
- Support cancel of scheduled VM validations when provider is removed.  Immediate, cleaner shutdown.
- Tuned settings.
Some minor logging adjustments.
This is critical to supporting very large Providers.
> Improved policy agent integration.

- pkg/controller/plan/migration.go
Backport of https://github.com/konveyor/forklift-controller/pull/266
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953145
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1959731
> BZ 1959731 - Fix logic error w/ kept VMs in Migration.begin()

- pkg/controller/provider/container/vsphere/watch.go
- pkg/controller/validation/policy/client.go
- pkg/settings/policy.go
> 2.0 backport: Fix vsphere validation search.

- pkg/controller/provider/container/vsphere/watch.go
- pkg/controller/validation/policy/client.go
> Backport pr272 re: pass workload to validation service.

- pkg/controller/provider/container/ovirt/client.go
- pkg/controller/provider/container/ovirt/model.go
- pkg/controller/provider/container/ovirt/resource.go
- pkg/controller/provider/model/ovirt/doc.go
- pkg/controller/provider/model/ovirt/model.go
- pkg/controller/provider/model/ovirt/tree.go
- pkg/controller/provider/web/ovirt/cluster.go
- pkg/controller/provider/web/ovirt/disk.go
- pkg/controller/provider/web/ovirt/doc.go
- pkg/controller/provider/web/ovirt/host.go
- pkg/controller/provider/web/ovirt/nicprofile.go
- pkg/controller/provider/web/ovirt/provider.go
- pkg/controller/provider/web/ovirt/tree.go
- pkg/controller/provider/web/ovirt/vm.go
Add more oVirt inventory properties.
Inventory Disks.
Fixed detail in tree navigator and node builder.
> Add more oVirt inventory properties.

- pkg/controller/provider/container/ovirt/resource.go
- pkg/controller/provider/model/ovirt/model.go
- pkg/controller/provider/web/ovirt/tree.go
- pkg/controller/provider/web/ovirt/vm.go
Formatting (go fmt) missed in previous PR.
> Formatting.

- pkg/controller/provider/container/ovirt/model.go
- pkg/controller/provider/container/ovirt/resource.go
- pkg/controller/provider/model/base/model.go
- pkg/controller/provider/model/ovirt/doc.go
- pkg/controller/provider/model/ovirt/model.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/ovirt/cluster.go
- pkg/controller/provider/web/ovirt/disk.go
- pkg/controller/provider/web/ovirt/diskprofile.go
- pkg/controller/provider/web/ovirt/doc.go
- pkg/controller/provider/web/ovirt/nicprofile.go
- pkg/controller/provider/web/ovirt/resource.go
- pkg/controller/provider/web/ovirt/tree.go
- pkg/controller/provider/web/ovirt/vm.go
- pkg/controller/provider/web/ovirt/workload.go
_"Added a ton of properties."_
Add mainly, VM, Host, NIC and Disk fields.
Add DiskProfile.
Add revision management and concerns support.
update `workload`.
> Additional oVirt fields.

- pkg/controller/provider/web/ovirt/disk.go
The Disk.Profile may be optional.
> Re-add Disk.StorageDomain.

- pkg/controller/provider/container/ovirt/reconciler.go
- pkg/controller/provider/container/ovirt/watch.go
- pkg/controller/provider/model/ovirt/model.go
- pkg/controller/validation/policy/client.go
Add oVirt validation service (policy-agent) integration.
> Validate oVirt VMs.

- pkg/controller/plan/migration.go
https://bugzilla.redhat.com/show_bug.cgi?id=1953727
> Set phases on the DiskTransfer step

- pkg/controller/host/handler/vsphere/handler.go
- pkg/controller/host/validation.go
- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ovirt/validator.go
- pkg/controller/plan/adapter/vsphere/validator.go
- pkg/controller/plan/validation.go
* Update the Host in the inventory if its InMaintenanceMode value has changed.
* Add a warning condition to the Host CR if it's in maintenance mode.
* Add a warning condition to the Plan CR if any of its VMs are on hosts which are in maintenance mode.
> Host maintenance mode validations

- go.mod
- go.sum
- pkg/controller/provider/container/ovirt/model.go
- pkg/controller/provider/container/ovirt/reconciler.go
- pkg/controller/provider/container/ovirt/watch.go
- pkg/controller/provider/container/vsphere/watch.go
Compat with simpler filebacked API released in controller v0.4.4.
> Compat with simpler filebacked API.

- pkg/controller/provider/container/ovirt/model.go
- pkg/controller/provider/container/ovirt/reconciler.go
- pkg/controller/provider/container/ovirt/watch.go
Added (more) oVirt event handling.
> oVirt part 8.

- pkg/controller/provider/container/ovirt/watch.go
> Fix build.

- pkg/controller/map/network/validation.go
Found/Fix items listed in DestinationNetworkNotValid (reason=NotFound) condition while verifying Bug:1971259.
> Fix items listed in DestinationNetworkNotValid (reason=NotFound) condition.

- pkg/controller/provider/container/ovirt/model.go
- pkg/controller/provider/container/ovirt/reconciler.go
Fix oVirt event handling holds transaction while fetching data from RHV.
This is really bad because the RHV API can block or be slow.
The design is to process events in (2) phases.
1. call Adapter.Apply(*Event) on each adapter registered to handle the event which will fetch data using the provider API and return a stateful `Updater`.
1. begin a transaction and _call_ each Updater.
> Fix oVirt event handling holds transaction while fetching data.

- go.mod
- go.sum
Provides greatly reduced memory footprint in container.Collection used by oVirt event handling.
Provided by enhancements in controller v0.4.6.
> Reduced memory footprint in oVirt event handling.

- pkg/controller/provider/container/ovirt/model.go
- pkg/controller/provider/container/ovirt/resource.go
- pkg/controller/provider/model/ovirt/model.go
- pkg/controller/provider/web/ovirt/disk.go
- pkg/controller/provider/web/ovirt/vm.go
Added VM, vNIC and Disk properties needed for validation.
> Added VM, vNIC and Disk properties needed for validation.

- pkg/controller/provider/container/ovirt/resource.go
- pkg/controller/provider/model/ovirt/model.go
- pkg/controller/provider/web/ovirt/vm.go
Add ovirt VM.stateless property needed for validation rule.
> Add ovirt VM.stateless property.

- pkg/controller/map/network/validation.go
Validate NAD references include namespace.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1971259
> Validate NAD refs include namespace.

- pkg/controller/provider/container/ovirt/resource.go
- pkg/controller/provider/model/ovirt/model.go
- pkg/controller/provider/web/ovirt/nicprofile.go
Fix usbEnabled and vNIC profile custom properties needed for validation.
The vNIC custom properties should have been modeled on the profile not the vNIC.
https://bugzilla.redhat.com/show_bug.cgi?id=1980451
> Fix usbEnabled and vNIC custom properties.

- pkg/controller/provider/container/ovirt/watch.go
Use oVirt validation endpoint.
> Use oVirt validation endpoint.

- Dockerfile
The `ubi8/ubi-micro` container image only weighs 39.1 MB, against 105 MB for the `ubi8/ubi-minimal` image. With this pull request, the total size of the controller image decreases from 156 MB to 89.9 MB. This will reduce download time and save space on the nodes where the controller runs.
At the same time, this pull request updates Golang to version 1.5.13, the latest available version.
I have built the image and tested it in a live cluster. No error, after a few tests.
> Use ubi8-micro as base image. Update Golang to 1.15.13.

- pkg/controller/provider/container/ovirt/reconciler.go
The RHV data collector is holding a DB transaction for the duration of listing all of the RHV collections which can take a long time.  A GET of /providers?detail=1 API request attempts a `SELECT COUNT(*)...` which requires the sqlite3 DB lock which has a default 5 second timeout.  The fix here is to stop holding transaction open while fetching data but instead fetch the data and then briefly hold the transaction to insert the already fetched data.
This is a healthy change in general and more in line with how the vSphere data collector works.
Note: There is a promising [effort](https://github.com/konveyor/controller/pull/89) _in-progress_ in konveyor/controller to improve concurrency in how the model layer uses sqlite3.
https://bugzilla.redhat.com/show_bug.cgi?id=1981771
``` …
```
> Fix "database is locked" error on GET provider with detail."

- go.mod
- go.sum
Controller v0.5.0 using sqlite3 journal-mode=WAL for better concurrency.
https://bugzilla.redhat.com/show_bug.cgi?id=1981771
> Controller v0.5.0 using sqlite3 journal-mode=WAL for better concurrency.

- pkg/controller/provider/web/base/auth.go
Authenticate token has (get) on provider secret (instead of "*" on Provider).
> Authenticate token has (get) on provider secret.

- pkg/controller/plan/migration.go
This PR causes the ImageConversion step to only be added to vSphere VM pipelines, and causes the ImportCreated phase to end when the DiskTransfer step is completed for VMs that don't have the ImageConversion step.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1980628
> Remove ImageConversion step from oVirt pipeline

- pkg/controller/provider/web/base/auth.go
Effectively reverts konveyor/forklift-controller#329 add logging.
This PR attempted to improve _securty_ but is broken for the `host` provider which has no Secret.  We can make further improvements in the next release.
> Revert 329 improved

- pkg/controller/provider/container/ovirt/model.go
Add missing ovirt events identified by RHV team.
> Add missing ovirt events.

- pkg/controller/plan/validation.go
https://bugzilla.redhat.com/show_bug.cgi?id=1993140
> Properly set maintenance mode condition on the plan

- pkg/controller/host/validation.go
Fix formatting missed in previous PR.
> Fix formatting.

- pkg/controller/provider/container/ovirt/model.go
Per Arik Hadas on RHV team - _"We got reports from backup vendors that this mechanism may be problematic (e.g., a VM that was reported in the first page got removed and so one of the VMs that were supposed to be returned as part of the second page might not be included when we query the second page)"_
The oVirt API has serious performance problems when fetching VMs using _follows_ to get sub-collection resources.  This has been improved by [1992686](https://bugzilla.redhat.com/show_bug.cgi?id=1992686).  The RH scale team strongly recommended that MTV fetch VMs in pages to prevent _crushing_ the RHV database. 
Although _crushing_ RHV isn't good either, missing data (VMs) is unacceptable.
> Discontinue fetching oVirt VMs in pages.

- pkg/controller/provider/web/ovirt/client.go
Needed to support using Workloads in the oVirt builder.
> Support Workloads in oVirt Resolver and Finder

- pkg/controller/plan/migration.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2012732
> Count precopy successes and failures

- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/adapter/vsphere/builder.go
https://bugzilla.redhat.com/show_bug.cgi?id=2012130
> Fix pointer bug in ovirt builder's mapDisks

- pkg/controller/provider/web/ovirt/vm.go
- pkg/controller/provider/web/vsphere/vm.go
Moved VM.status and VM.powerState to detail=1 needed by UI.
> Moved VM.status and VM.powerState to detail=1.

- pkg/controller/plan/kubevirt.go
- pkg/settings/features.go
Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2016290
> Make retaining importer pods optional for warm migration

- config/crds/forklift.konveyor.io_migrations.yaml
- config/crds/forklift.konveyor.io_plans.yaml
- config/forklift.konveyor.io_migrations.yaml
- config/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan/vm.go
https://bugzilla.redhat.com/show_bug.cgi?id=2012564
> Bug 2012564: VMStatus.RestorePowerState is not a required field

- pkg/controller/plan/migration.go
If the CDI importer pod for a datavolume isn't found while trying to update the status of the disk transfer, then we should just log and continue rather than causing the migration to fail. CDI recreates the importer pod if it's removed while the import is in progress, so we can expect the importer pod not being found to be a transient issue.
> Bug 2024138: Log rather than fail if importer pod isn't found

- pkg/controller/plan/kubevirt.go
With the change to using StorageProfiles, the DV specification no longer is guaranteed to contain a value for VolumeMode or AccessModes. We need to look at the created PVC to discover which modes were used, so that the libvirt domain can be created correctly.
https://bugzilla.redhat.com/show_bug.cgi?id=2036482
> Bug 2036482: Retrieve PVCs when listing VMs and DVs

- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ovirt/client.go
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/client.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
- pkg/controller/provider/container/vsphere/model.go
https://issues.redhat.com/browse/MTV-138
https://bugzilla.redhat.com/show_bug.cgi?id=1942651
> Bug 1942651: vSphere - determine individual change IDs for each disk

- pkg/controller/plan/adapter/ovirt/client.go
Bug 2048505 - warm migration from RHV failing.
> Pass oVirt disk snapshot IDs for warm migration.

- pkg/controller/plan/migration.go
https://bugzilla.redhat.com/show_bug.cgi?id=2024228
> Bug 2024228: Improve detail of disk transfer status reporting

- pkg/controller/plan/migration.go
Updating migration Steps with Phase names providing migration progress
in Forklift UI.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2047460
> Report Migration progress to Step Phase

- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/provider/container/vsphere/collector.go
- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/network.go
https://bugzilla.redhat.com/show_bug.cgi?id=2068627
Cherry-picked from main.
> Bug 2068627: vSphere: Fix mapping NICs assigned to DvPortGroups

- Dockerfile
- go-toolset and ubi8-minimal updates
> Refresh base images

- Dockerfile
> Backport #431 for v2.3.2

- pkg/controller/plan/kubevirt.go
Just refactoring. No changes in behavior.
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>
> Simplify code around ConfigMap creation

- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ovirt/client.go
- pkg/controller/plan/adapter/vsphere/client.go
- pkg/controller/plan/migration.go
Backport pull request #443 for release 2.3.3, for RHBZ#2055201.
> Backport #443 for 2.3.3 (bug 2055201).

- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
https://bugzilla.redhat.com/show_bug.cgi?id=2121851
> [Backport v2.3.3] GetImporterPod: Get pod name from PVC annotation 

- pkg/controller/plan/adapter/ovirt/client.go
Bug-Url: https://bugzilla.redhat.com/2125889
> ovirt: use kvpair when creating error messages

- pkg/controller/plan/adapter/ovirt/client.go
Backport fix for https://bugzilla.redhat.com/2125889 to 2.3.3.
> Backport #466 to release-v2.3.3
